
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AssessmentControl` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AssessmentControl
 * 
 */
export type AssessmentControlModel = runtime.Types.Result.DefaultSelection<Prisma.$AssessmentControlPayload>

export type AggregateAssessmentControl = {
  _count: AssessmentControlCountAggregateOutputType | null
  _min: AssessmentControlMinAggregateOutputType | null
  _max: AssessmentControlMaxAggregateOutputType | null
}

export type AssessmentControlMinAggregateOutputType = {
  id: string | null
  assessmentId: string | null
  controlId: string | null
  createdAt: Date | null
}

export type AssessmentControlMaxAggregateOutputType = {
  id: string | null
  assessmentId: string | null
  controlId: string | null
  createdAt: Date | null
}

export type AssessmentControlCountAggregateOutputType = {
  id: number
  assessmentId: number
  controlId: number
  createdAt: number
  _all: number
}


export type AssessmentControlMinAggregateInputType = {
  id?: true
  assessmentId?: true
  controlId?: true
  createdAt?: true
}

export type AssessmentControlMaxAggregateInputType = {
  id?: true
  assessmentId?: true
  controlId?: true
  createdAt?: true
}

export type AssessmentControlCountAggregateInputType = {
  id?: true
  assessmentId?: true
  controlId?: true
  createdAt?: true
  _all?: true
}

export type AssessmentControlAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssessmentControl to aggregate.
   */
  where?: Prisma.AssessmentControlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssessmentControls to fetch.
   */
  orderBy?: Prisma.AssessmentControlOrderByWithRelationInput | Prisma.AssessmentControlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssessmentControlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssessmentControls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssessmentControls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AssessmentControls
  **/
  _count?: true | AssessmentControlCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssessmentControlMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssessmentControlMaxAggregateInputType
}

export type GetAssessmentControlAggregateType<T extends AssessmentControlAggregateArgs> = {
      [P in keyof T & keyof AggregateAssessmentControl]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssessmentControl[P]>
    : Prisma.GetScalarType<T[P], AggregateAssessmentControl[P]>
}




export type AssessmentControlGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssessmentControlWhereInput
  orderBy?: Prisma.AssessmentControlOrderByWithAggregationInput | Prisma.AssessmentControlOrderByWithAggregationInput[]
  by: Prisma.AssessmentControlScalarFieldEnum[] | Prisma.AssessmentControlScalarFieldEnum
  having?: Prisma.AssessmentControlScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssessmentControlCountAggregateInputType | true
  _min?: AssessmentControlMinAggregateInputType
  _max?: AssessmentControlMaxAggregateInputType
}

export type AssessmentControlGroupByOutputType = {
  id: string
  assessmentId: string
  controlId: string
  createdAt: Date
  _count: AssessmentControlCountAggregateOutputType | null
  _min: AssessmentControlMinAggregateOutputType | null
  _max: AssessmentControlMaxAggregateOutputType | null
}

export type GetAssessmentControlGroupByPayload<T extends AssessmentControlGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssessmentControlGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssessmentControlGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssessmentControlGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssessmentControlGroupByOutputType[P]>
      }
    >
  >



export type AssessmentControlWhereInput = {
  AND?: Prisma.AssessmentControlWhereInput | Prisma.AssessmentControlWhereInput[]
  OR?: Prisma.AssessmentControlWhereInput[]
  NOT?: Prisma.AssessmentControlWhereInput | Prisma.AssessmentControlWhereInput[]
  id?: Prisma.StringFilter<"AssessmentControl"> | string
  assessmentId?: Prisma.StringFilter<"AssessmentControl"> | string
  controlId?: Prisma.StringFilter<"AssessmentControl"> | string
  createdAt?: Prisma.DateTimeFilter<"AssessmentControl"> | Date | string
  control?: Prisma.XOR<Prisma.ControlScalarRelationFilter, Prisma.ControlWhereInput>
  assessment?: Prisma.XOR<Prisma.AssessmentScalarRelationFilter, Prisma.AssessmentWhereInput>
}

export type AssessmentControlOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  controlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  control?: Prisma.ControlOrderByWithRelationInput
  assessment?: Prisma.AssessmentOrderByWithRelationInput
}

export type AssessmentControlWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  assessmentId_controlId?: Prisma.AssessmentControlAssessmentIdControlIdCompoundUniqueInput
  AND?: Prisma.AssessmentControlWhereInput | Prisma.AssessmentControlWhereInput[]
  OR?: Prisma.AssessmentControlWhereInput[]
  NOT?: Prisma.AssessmentControlWhereInput | Prisma.AssessmentControlWhereInput[]
  assessmentId?: Prisma.StringFilter<"AssessmentControl"> | string
  controlId?: Prisma.StringFilter<"AssessmentControl"> | string
  createdAt?: Prisma.DateTimeFilter<"AssessmentControl"> | Date | string
  control?: Prisma.XOR<Prisma.ControlScalarRelationFilter, Prisma.ControlWhereInput>
  assessment?: Prisma.XOR<Prisma.AssessmentScalarRelationFilter, Prisma.AssessmentWhereInput>
}, "id" | "assessmentId_controlId">

export type AssessmentControlOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  controlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AssessmentControlCountOrderByAggregateInput
  _max?: Prisma.AssessmentControlMaxOrderByAggregateInput
  _min?: Prisma.AssessmentControlMinOrderByAggregateInput
}

export type AssessmentControlScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssessmentControlScalarWhereWithAggregatesInput | Prisma.AssessmentControlScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssessmentControlScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssessmentControlScalarWhereWithAggregatesInput | Prisma.AssessmentControlScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AssessmentControl"> | string
  assessmentId?: Prisma.StringWithAggregatesFilter<"AssessmentControl"> | string
  controlId?: Prisma.StringWithAggregatesFilter<"AssessmentControl"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AssessmentControl"> | Date | string
}

export type AssessmentControlCreateInput = {
  id?: string
  createdAt?: Date | string
  control: Prisma.ControlCreateNestedOneWithoutAssessmentControlsInput
  assessment: Prisma.AssessmentCreateNestedOneWithoutAssessmentControlsInput
}

export type AssessmentControlUncheckedCreateInput = {
  id?: string
  assessmentId: string
  controlId: string
  createdAt?: Date | string
}

export type AssessmentControlUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  control?: Prisma.ControlUpdateOneRequiredWithoutAssessmentControlsNestedInput
  assessment?: Prisma.AssessmentUpdateOneRequiredWithoutAssessmentControlsNestedInput
}

export type AssessmentControlUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assessmentId?: Prisma.StringFieldUpdateOperationsInput | string
  controlId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentControlCreateManyInput = {
  id?: string
  assessmentId: string
  controlId: string
  createdAt?: Date | string
}

export type AssessmentControlUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentControlUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assessmentId?: Prisma.StringFieldUpdateOperationsInput | string
  controlId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentControlListRelationFilter = {
  every?: Prisma.AssessmentControlWhereInput
  some?: Prisma.AssessmentControlWhereInput
  none?: Prisma.AssessmentControlWhereInput
}

export type AssessmentControlOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssessmentControlAssessmentIdControlIdCompoundUniqueInput = {
  assessmentId: string
  controlId: string
}

export type AssessmentControlCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  controlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssessmentControlMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  controlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssessmentControlMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  controlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssessmentControlCreateNestedManyWithoutControlInput = {
  create?: Prisma.XOR<Prisma.AssessmentControlCreateWithoutControlInput, Prisma.AssessmentControlUncheckedCreateWithoutControlInput> | Prisma.AssessmentControlCreateWithoutControlInput[] | Prisma.AssessmentControlUncheckedCreateWithoutControlInput[]
  connectOrCreate?: Prisma.AssessmentControlCreateOrConnectWithoutControlInput | Prisma.AssessmentControlCreateOrConnectWithoutControlInput[]
  createMany?: Prisma.AssessmentControlCreateManyControlInputEnvelope
  connect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
}

export type AssessmentControlUncheckedCreateNestedManyWithoutControlInput = {
  create?: Prisma.XOR<Prisma.AssessmentControlCreateWithoutControlInput, Prisma.AssessmentControlUncheckedCreateWithoutControlInput> | Prisma.AssessmentControlCreateWithoutControlInput[] | Prisma.AssessmentControlUncheckedCreateWithoutControlInput[]
  connectOrCreate?: Prisma.AssessmentControlCreateOrConnectWithoutControlInput | Prisma.AssessmentControlCreateOrConnectWithoutControlInput[]
  createMany?: Prisma.AssessmentControlCreateManyControlInputEnvelope
  connect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
}

export type AssessmentControlUpdateManyWithoutControlNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentControlCreateWithoutControlInput, Prisma.AssessmentControlUncheckedCreateWithoutControlInput> | Prisma.AssessmentControlCreateWithoutControlInput[] | Prisma.AssessmentControlUncheckedCreateWithoutControlInput[]
  connectOrCreate?: Prisma.AssessmentControlCreateOrConnectWithoutControlInput | Prisma.AssessmentControlCreateOrConnectWithoutControlInput[]
  upsert?: Prisma.AssessmentControlUpsertWithWhereUniqueWithoutControlInput | Prisma.AssessmentControlUpsertWithWhereUniqueWithoutControlInput[]
  createMany?: Prisma.AssessmentControlCreateManyControlInputEnvelope
  set?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  disconnect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  delete?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  connect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  update?: Prisma.AssessmentControlUpdateWithWhereUniqueWithoutControlInput | Prisma.AssessmentControlUpdateWithWhereUniqueWithoutControlInput[]
  updateMany?: Prisma.AssessmentControlUpdateManyWithWhereWithoutControlInput | Prisma.AssessmentControlUpdateManyWithWhereWithoutControlInput[]
  deleteMany?: Prisma.AssessmentControlScalarWhereInput | Prisma.AssessmentControlScalarWhereInput[]
}

export type AssessmentControlUncheckedUpdateManyWithoutControlNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentControlCreateWithoutControlInput, Prisma.AssessmentControlUncheckedCreateWithoutControlInput> | Prisma.AssessmentControlCreateWithoutControlInput[] | Prisma.AssessmentControlUncheckedCreateWithoutControlInput[]
  connectOrCreate?: Prisma.AssessmentControlCreateOrConnectWithoutControlInput | Prisma.AssessmentControlCreateOrConnectWithoutControlInput[]
  upsert?: Prisma.AssessmentControlUpsertWithWhereUniqueWithoutControlInput | Prisma.AssessmentControlUpsertWithWhereUniqueWithoutControlInput[]
  createMany?: Prisma.AssessmentControlCreateManyControlInputEnvelope
  set?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  disconnect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  delete?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  connect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  update?: Prisma.AssessmentControlUpdateWithWhereUniqueWithoutControlInput | Prisma.AssessmentControlUpdateWithWhereUniqueWithoutControlInput[]
  updateMany?: Prisma.AssessmentControlUpdateManyWithWhereWithoutControlInput | Prisma.AssessmentControlUpdateManyWithWhereWithoutControlInput[]
  deleteMany?: Prisma.AssessmentControlScalarWhereInput | Prisma.AssessmentControlScalarWhereInput[]
}

export type AssessmentControlCreateNestedManyWithoutAssessmentInput = {
  create?: Prisma.XOR<Prisma.AssessmentControlCreateWithoutAssessmentInput, Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput> | Prisma.AssessmentControlCreateWithoutAssessmentInput[] | Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput[]
  connectOrCreate?: Prisma.AssessmentControlCreateOrConnectWithoutAssessmentInput | Prisma.AssessmentControlCreateOrConnectWithoutAssessmentInput[]
  createMany?: Prisma.AssessmentControlCreateManyAssessmentInputEnvelope
  connect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
}

export type AssessmentControlUncheckedCreateNestedManyWithoutAssessmentInput = {
  create?: Prisma.XOR<Prisma.AssessmentControlCreateWithoutAssessmentInput, Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput> | Prisma.AssessmentControlCreateWithoutAssessmentInput[] | Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput[]
  connectOrCreate?: Prisma.AssessmentControlCreateOrConnectWithoutAssessmentInput | Prisma.AssessmentControlCreateOrConnectWithoutAssessmentInput[]
  createMany?: Prisma.AssessmentControlCreateManyAssessmentInputEnvelope
  connect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
}

export type AssessmentControlUpdateManyWithoutAssessmentNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentControlCreateWithoutAssessmentInput, Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput> | Prisma.AssessmentControlCreateWithoutAssessmentInput[] | Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput[]
  connectOrCreate?: Prisma.AssessmentControlCreateOrConnectWithoutAssessmentInput | Prisma.AssessmentControlCreateOrConnectWithoutAssessmentInput[]
  upsert?: Prisma.AssessmentControlUpsertWithWhereUniqueWithoutAssessmentInput | Prisma.AssessmentControlUpsertWithWhereUniqueWithoutAssessmentInput[]
  createMany?: Prisma.AssessmentControlCreateManyAssessmentInputEnvelope
  set?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  disconnect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  delete?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  connect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  update?: Prisma.AssessmentControlUpdateWithWhereUniqueWithoutAssessmentInput | Prisma.AssessmentControlUpdateWithWhereUniqueWithoutAssessmentInput[]
  updateMany?: Prisma.AssessmentControlUpdateManyWithWhereWithoutAssessmentInput | Prisma.AssessmentControlUpdateManyWithWhereWithoutAssessmentInput[]
  deleteMany?: Prisma.AssessmentControlScalarWhereInput | Prisma.AssessmentControlScalarWhereInput[]
}

export type AssessmentControlUncheckedUpdateManyWithoutAssessmentNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentControlCreateWithoutAssessmentInput, Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput> | Prisma.AssessmentControlCreateWithoutAssessmentInput[] | Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput[]
  connectOrCreate?: Prisma.AssessmentControlCreateOrConnectWithoutAssessmentInput | Prisma.AssessmentControlCreateOrConnectWithoutAssessmentInput[]
  upsert?: Prisma.AssessmentControlUpsertWithWhereUniqueWithoutAssessmentInput | Prisma.AssessmentControlUpsertWithWhereUniqueWithoutAssessmentInput[]
  createMany?: Prisma.AssessmentControlCreateManyAssessmentInputEnvelope
  set?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  disconnect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  delete?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  connect?: Prisma.AssessmentControlWhereUniqueInput | Prisma.AssessmentControlWhereUniqueInput[]
  update?: Prisma.AssessmentControlUpdateWithWhereUniqueWithoutAssessmentInput | Prisma.AssessmentControlUpdateWithWhereUniqueWithoutAssessmentInput[]
  updateMany?: Prisma.AssessmentControlUpdateManyWithWhereWithoutAssessmentInput | Prisma.AssessmentControlUpdateManyWithWhereWithoutAssessmentInput[]
  deleteMany?: Prisma.AssessmentControlScalarWhereInput | Prisma.AssessmentControlScalarWhereInput[]
}

export type AssessmentControlCreateWithoutControlInput = {
  id?: string
  createdAt?: Date | string
  assessment: Prisma.AssessmentCreateNestedOneWithoutAssessmentControlsInput
}

export type AssessmentControlUncheckedCreateWithoutControlInput = {
  id?: string
  assessmentId: string
  createdAt?: Date | string
}

export type AssessmentControlCreateOrConnectWithoutControlInput = {
  where: Prisma.AssessmentControlWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentControlCreateWithoutControlInput, Prisma.AssessmentControlUncheckedCreateWithoutControlInput>
}

export type AssessmentControlCreateManyControlInputEnvelope = {
  data: Prisma.AssessmentControlCreateManyControlInput | Prisma.AssessmentControlCreateManyControlInput[]
}

export type AssessmentControlUpsertWithWhereUniqueWithoutControlInput = {
  where: Prisma.AssessmentControlWhereUniqueInput
  update: Prisma.XOR<Prisma.AssessmentControlUpdateWithoutControlInput, Prisma.AssessmentControlUncheckedUpdateWithoutControlInput>
  create: Prisma.XOR<Prisma.AssessmentControlCreateWithoutControlInput, Prisma.AssessmentControlUncheckedCreateWithoutControlInput>
}

export type AssessmentControlUpdateWithWhereUniqueWithoutControlInput = {
  where: Prisma.AssessmentControlWhereUniqueInput
  data: Prisma.XOR<Prisma.AssessmentControlUpdateWithoutControlInput, Prisma.AssessmentControlUncheckedUpdateWithoutControlInput>
}

export type AssessmentControlUpdateManyWithWhereWithoutControlInput = {
  where: Prisma.AssessmentControlScalarWhereInput
  data: Prisma.XOR<Prisma.AssessmentControlUpdateManyMutationInput, Prisma.AssessmentControlUncheckedUpdateManyWithoutControlInput>
}

export type AssessmentControlScalarWhereInput = {
  AND?: Prisma.AssessmentControlScalarWhereInput | Prisma.AssessmentControlScalarWhereInput[]
  OR?: Prisma.AssessmentControlScalarWhereInput[]
  NOT?: Prisma.AssessmentControlScalarWhereInput | Prisma.AssessmentControlScalarWhereInput[]
  id?: Prisma.StringFilter<"AssessmentControl"> | string
  assessmentId?: Prisma.StringFilter<"AssessmentControl"> | string
  controlId?: Prisma.StringFilter<"AssessmentControl"> | string
  createdAt?: Prisma.DateTimeFilter<"AssessmentControl"> | Date | string
}

export type AssessmentControlCreateWithoutAssessmentInput = {
  id?: string
  createdAt?: Date | string
  control: Prisma.ControlCreateNestedOneWithoutAssessmentControlsInput
}

export type AssessmentControlUncheckedCreateWithoutAssessmentInput = {
  id?: string
  controlId: string
  createdAt?: Date | string
}

export type AssessmentControlCreateOrConnectWithoutAssessmentInput = {
  where: Prisma.AssessmentControlWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentControlCreateWithoutAssessmentInput, Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput>
}

export type AssessmentControlCreateManyAssessmentInputEnvelope = {
  data: Prisma.AssessmentControlCreateManyAssessmentInput | Prisma.AssessmentControlCreateManyAssessmentInput[]
}

export type AssessmentControlUpsertWithWhereUniqueWithoutAssessmentInput = {
  where: Prisma.AssessmentControlWhereUniqueInput
  update: Prisma.XOR<Prisma.AssessmentControlUpdateWithoutAssessmentInput, Prisma.AssessmentControlUncheckedUpdateWithoutAssessmentInput>
  create: Prisma.XOR<Prisma.AssessmentControlCreateWithoutAssessmentInput, Prisma.AssessmentControlUncheckedCreateWithoutAssessmentInput>
}

export type AssessmentControlUpdateWithWhereUniqueWithoutAssessmentInput = {
  where: Prisma.AssessmentControlWhereUniqueInput
  data: Prisma.XOR<Prisma.AssessmentControlUpdateWithoutAssessmentInput, Prisma.AssessmentControlUncheckedUpdateWithoutAssessmentInput>
}

export type AssessmentControlUpdateManyWithWhereWithoutAssessmentInput = {
  where: Prisma.AssessmentControlScalarWhereInput
  data: Prisma.XOR<Prisma.AssessmentControlUpdateManyMutationInput, Prisma.AssessmentControlUncheckedUpdateManyWithoutAssessmentInput>
}

export type AssessmentControlCreateManyControlInput = {
  id?: string
  assessmentId: string
  createdAt?: Date | string
}

export type AssessmentControlUpdateWithoutControlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assessment?: Prisma.AssessmentUpdateOneRequiredWithoutAssessmentControlsNestedInput
}

export type AssessmentControlUncheckedUpdateWithoutControlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assessmentId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentControlUncheckedUpdateManyWithoutControlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assessmentId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentControlCreateManyAssessmentInput = {
  id?: string
  controlId: string
  createdAt?: Date | string
}

export type AssessmentControlUpdateWithoutAssessmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  control?: Prisma.ControlUpdateOneRequiredWithoutAssessmentControlsNestedInput
}

export type AssessmentControlUncheckedUpdateWithoutAssessmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  controlId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentControlUncheckedUpdateManyWithoutAssessmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  controlId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AssessmentControlSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assessmentId?: boolean
  controlId?: boolean
  createdAt?: boolean
  control?: boolean | Prisma.ControlDefaultArgs<ExtArgs>
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessmentControl"]>

export type AssessmentControlSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assessmentId?: boolean
  controlId?: boolean
  createdAt?: boolean
  control?: boolean | Prisma.ControlDefaultArgs<ExtArgs>
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessmentControl"]>

export type AssessmentControlSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assessmentId?: boolean
  controlId?: boolean
  createdAt?: boolean
  control?: boolean | Prisma.ControlDefaultArgs<ExtArgs>
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessmentControl"]>

export type AssessmentControlSelectScalar = {
  id?: boolean
  assessmentId?: boolean
  controlId?: boolean
  createdAt?: boolean
}

export type AssessmentControlOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "assessmentId" | "controlId" | "createdAt", ExtArgs["result"]["assessmentControl"]>
export type AssessmentControlInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  control?: boolean | Prisma.ControlDefaultArgs<ExtArgs>
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
}
export type AssessmentControlIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  control?: boolean | Prisma.ControlDefaultArgs<ExtArgs>
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
}
export type AssessmentControlIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  control?: boolean | Prisma.ControlDefaultArgs<ExtArgs>
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
}

export type $AssessmentControlPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AssessmentControl"
  objects: {
    control: Prisma.$ControlPayload<ExtArgs>
    assessment: Prisma.$AssessmentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    assessmentId: string
    controlId: string
    createdAt: Date
  }, ExtArgs["result"]["assessmentControl"]>
  composites: {}
}

export type AssessmentControlGetPayload<S extends boolean | null | undefined | AssessmentControlDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload, S>

export type AssessmentControlCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssessmentControlFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssessmentControlCountAggregateInputType | true
  }

export interface AssessmentControlDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AssessmentControl'], meta: { name: 'AssessmentControl' } }
  /**
   * Find zero or one AssessmentControl that matches the filter.
   * @param {AssessmentControlFindUniqueArgs} args - Arguments to find a AssessmentControl
   * @example
   * // Get one AssessmentControl
   * const assessmentControl = await prisma.assessmentControl.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssessmentControlFindUniqueArgs>(args: Prisma.SelectSubset<T, AssessmentControlFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssessmentControlClient<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AssessmentControl that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssessmentControlFindUniqueOrThrowArgs} args - Arguments to find a AssessmentControl
   * @example
   * // Get one AssessmentControl
   * const assessmentControl = await prisma.assessmentControl.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssessmentControlFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssessmentControlFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssessmentControlClient<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssessmentControl that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentControlFindFirstArgs} args - Arguments to find a AssessmentControl
   * @example
   * // Get one AssessmentControl
   * const assessmentControl = await prisma.assessmentControl.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssessmentControlFindFirstArgs>(args?: Prisma.SelectSubset<T, AssessmentControlFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssessmentControlClient<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssessmentControl that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentControlFindFirstOrThrowArgs} args - Arguments to find a AssessmentControl
   * @example
   * // Get one AssessmentControl
   * const assessmentControl = await prisma.assessmentControl.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssessmentControlFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssessmentControlFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssessmentControlClient<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AssessmentControls that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentControlFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AssessmentControls
   * const assessmentControls = await prisma.assessmentControl.findMany()
   * 
   * // Get first 10 AssessmentControls
   * const assessmentControls = await prisma.assessmentControl.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assessmentControlWithIdOnly = await prisma.assessmentControl.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AssessmentControlFindManyArgs>(args?: Prisma.SelectSubset<T, AssessmentControlFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AssessmentControl.
   * @param {AssessmentControlCreateArgs} args - Arguments to create a AssessmentControl.
   * @example
   * // Create one AssessmentControl
   * const AssessmentControl = await prisma.assessmentControl.create({
   *   data: {
   *     // ... data to create a AssessmentControl
   *   }
   * })
   * 
   */
  create<T extends AssessmentControlCreateArgs>(args: Prisma.SelectSubset<T, AssessmentControlCreateArgs<ExtArgs>>): Prisma.Prisma__AssessmentControlClient<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AssessmentControls.
   * @param {AssessmentControlCreateManyArgs} args - Arguments to create many AssessmentControls.
   * @example
   * // Create many AssessmentControls
   * const assessmentControl = await prisma.assessmentControl.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssessmentControlCreateManyArgs>(args?: Prisma.SelectSubset<T, AssessmentControlCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AssessmentControls and returns the data saved in the database.
   * @param {AssessmentControlCreateManyAndReturnArgs} args - Arguments to create many AssessmentControls.
   * @example
   * // Create many AssessmentControls
   * const assessmentControl = await prisma.assessmentControl.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AssessmentControls and only return the `id`
   * const assessmentControlWithIdOnly = await prisma.assessmentControl.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssessmentControlCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssessmentControlCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AssessmentControl.
   * @param {AssessmentControlDeleteArgs} args - Arguments to delete one AssessmentControl.
   * @example
   * // Delete one AssessmentControl
   * const AssessmentControl = await prisma.assessmentControl.delete({
   *   where: {
   *     // ... filter to delete one AssessmentControl
   *   }
   * })
   * 
   */
  delete<T extends AssessmentControlDeleteArgs>(args: Prisma.SelectSubset<T, AssessmentControlDeleteArgs<ExtArgs>>): Prisma.Prisma__AssessmentControlClient<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AssessmentControl.
   * @param {AssessmentControlUpdateArgs} args - Arguments to update one AssessmentControl.
   * @example
   * // Update one AssessmentControl
   * const assessmentControl = await prisma.assessmentControl.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssessmentControlUpdateArgs>(args: Prisma.SelectSubset<T, AssessmentControlUpdateArgs<ExtArgs>>): Prisma.Prisma__AssessmentControlClient<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AssessmentControls.
   * @param {AssessmentControlDeleteManyArgs} args - Arguments to filter AssessmentControls to delete.
   * @example
   * // Delete a few AssessmentControls
   * const { count } = await prisma.assessmentControl.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssessmentControlDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssessmentControlDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssessmentControls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentControlUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AssessmentControls
   * const assessmentControl = await prisma.assessmentControl.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssessmentControlUpdateManyArgs>(args: Prisma.SelectSubset<T, AssessmentControlUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssessmentControls and returns the data updated in the database.
   * @param {AssessmentControlUpdateManyAndReturnArgs} args - Arguments to update many AssessmentControls.
   * @example
   * // Update many AssessmentControls
   * const assessmentControl = await prisma.assessmentControl.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AssessmentControls and only return the `id`
   * const assessmentControlWithIdOnly = await prisma.assessmentControl.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssessmentControlUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssessmentControlUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AssessmentControl.
   * @param {AssessmentControlUpsertArgs} args - Arguments to update or create a AssessmentControl.
   * @example
   * // Update or create a AssessmentControl
   * const assessmentControl = await prisma.assessmentControl.upsert({
   *   create: {
   *     // ... data to create a AssessmentControl
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AssessmentControl we want to update
   *   }
   * })
   */
  upsert<T extends AssessmentControlUpsertArgs>(args: Prisma.SelectSubset<T, AssessmentControlUpsertArgs<ExtArgs>>): Prisma.Prisma__AssessmentControlClient<runtime.Types.Result.GetResult<Prisma.$AssessmentControlPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AssessmentControls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentControlCountArgs} args - Arguments to filter AssessmentControls to count.
   * @example
   * // Count the number of AssessmentControls
   * const count = await prisma.assessmentControl.count({
   *   where: {
   *     // ... the filter for the AssessmentControls we want to count
   *   }
   * })
  **/
  count<T extends AssessmentControlCountArgs>(
    args?: Prisma.Subset<T, AssessmentControlCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssessmentControlCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AssessmentControl.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentControlAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssessmentControlAggregateArgs>(args: Prisma.Subset<T, AssessmentControlAggregateArgs>): Prisma.PrismaPromise<GetAssessmentControlAggregateType<T>>

  /**
   * Group by AssessmentControl.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentControlGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssessmentControlGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssessmentControlGroupByArgs['orderBy'] }
      : { orderBy?: AssessmentControlGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssessmentControlGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssessmentControlGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AssessmentControl model
 */
readonly fields: AssessmentControlFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AssessmentControl.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssessmentControlClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  control<T extends Prisma.ControlDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ControlDefaultArgs<ExtArgs>>): Prisma.Prisma__ControlClient<runtime.Types.Result.GetResult<Prisma.$ControlPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  assessment<T extends Prisma.AssessmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssessmentDefaultArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AssessmentControl model
 */
export interface AssessmentControlFieldRefs {
  readonly id: Prisma.FieldRef<"AssessmentControl", 'String'>
  readonly assessmentId: Prisma.FieldRef<"AssessmentControl", 'String'>
  readonly controlId: Prisma.FieldRef<"AssessmentControl", 'String'>
  readonly createdAt: Prisma.FieldRef<"AssessmentControl", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AssessmentControl findUnique
 */
export type AssessmentControlFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentControl to fetch.
   */
  where: Prisma.AssessmentControlWhereUniqueInput
}

/**
 * AssessmentControl findUniqueOrThrow
 */
export type AssessmentControlFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentControl to fetch.
   */
  where: Prisma.AssessmentControlWhereUniqueInput
}

/**
 * AssessmentControl findFirst
 */
export type AssessmentControlFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentControl to fetch.
   */
  where?: Prisma.AssessmentControlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssessmentControls to fetch.
   */
  orderBy?: Prisma.AssessmentControlOrderByWithRelationInput | Prisma.AssessmentControlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssessmentControls.
   */
  cursor?: Prisma.AssessmentControlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssessmentControls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssessmentControls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssessmentControls.
   */
  distinct?: Prisma.AssessmentControlScalarFieldEnum | Prisma.AssessmentControlScalarFieldEnum[]
}

/**
 * AssessmentControl findFirstOrThrow
 */
export type AssessmentControlFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentControl to fetch.
   */
  where?: Prisma.AssessmentControlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssessmentControls to fetch.
   */
  orderBy?: Prisma.AssessmentControlOrderByWithRelationInput | Prisma.AssessmentControlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssessmentControls.
   */
  cursor?: Prisma.AssessmentControlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssessmentControls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssessmentControls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssessmentControls.
   */
  distinct?: Prisma.AssessmentControlScalarFieldEnum | Prisma.AssessmentControlScalarFieldEnum[]
}

/**
 * AssessmentControl findMany
 */
export type AssessmentControlFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentControls to fetch.
   */
  where?: Prisma.AssessmentControlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssessmentControls to fetch.
   */
  orderBy?: Prisma.AssessmentControlOrderByWithRelationInput | Prisma.AssessmentControlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AssessmentControls.
   */
  cursor?: Prisma.AssessmentControlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssessmentControls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssessmentControls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssessmentControls.
   */
  distinct?: Prisma.AssessmentControlScalarFieldEnum | Prisma.AssessmentControlScalarFieldEnum[]
}

/**
 * AssessmentControl create
 */
export type AssessmentControlCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * The data needed to create a AssessmentControl.
   */
  data: Prisma.XOR<Prisma.AssessmentControlCreateInput, Prisma.AssessmentControlUncheckedCreateInput>
}

/**
 * AssessmentControl createMany
 */
export type AssessmentControlCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AssessmentControls.
   */
  data: Prisma.AssessmentControlCreateManyInput | Prisma.AssessmentControlCreateManyInput[]
}

/**
 * AssessmentControl createManyAndReturn
 */
export type AssessmentControlCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * The data used to create many AssessmentControls.
   */
  data: Prisma.AssessmentControlCreateManyInput | Prisma.AssessmentControlCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AssessmentControl update
 */
export type AssessmentControlUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * The data needed to update a AssessmentControl.
   */
  data: Prisma.XOR<Prisma.AssessmentControlUpdateInput, Prisma.AssessmentControlUncheckedUpdateInput>
  /**
   * Choose, which AssessmentControl to update.
   */
  where: Prisma.AssessmentControlWhereUniqueInput
}

/**
 * AssessmentControl updateMany
 */
export type AssessmentControlUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AssessmentControls.
   */
  data: Prisma.XOR<Prisma.AssessmentControlUpdateManyMutationInput, Prisma.AssessmentControlUncheckedUpdateManyInput>
  /**
   * Filter which AssessmentControls to update
   */
  where?: Prisma.AssessmentControlWhereInput
  /**
   * Limit how many AssessmentControls to update.
   */
  limit?: number
}

/**
 * AssessmentControl updateManyAndReturn
 */
export type AssessmentControlUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * The data used to update AssessmentControls.
   */
  data: Prisma.XOR<Prisma.AssessmentControlUpdateManyMutationInput, Prisma.AssessmentControlUncheckedUpdateManyInput>
  /**
   * Filter which AssessmentControls to update
   */
  where?: Prisma.AssessmentControlWhereInput
  /**
   * Limit how many AssessmentControls to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AssessmentControl upsert
 */
export type AssessmentControlUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * The filter to search for the AssessmentControl to update in case it exists.
   */
  where: Prisma.AssessmentControlWhereUniqueInput
  /**
   * In case the AssessmentControl found by the `where` argument doesn't exist, create a new AssessmentControl with this data.
   */
  create: Prisma.XOR<Prisma.AssessmentControlCreateInput, Prisma.AssessmentControlUncheckedCreateInput>
  /**
   * In case the AssessmentControl was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssessmentControlUpdateInput, Prisma.AssessmentControlUncheckedUpdateInput>
}

/**
 * AssessmentControl delete
 */
export type AssessmentControlDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
  /**
   * Filter which AssessmentControl to delete.
   */
  where: Prisma.AssessmentControlWhereUniqueInput
}

/**
 * AssessmentControl deleteMany
 */
export type AssessmentControlDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssessmentControls to delete
   */
  where?: Prisma.AssessmentControlWhereInput
  /**
   * Limit how many AssessmentControls to delete.
   */
  limit?: number
}

/**
 * AssessmentControl without action
 */
export type AssessmentControlDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentControl
   */
  select?: Prisma.AssessmentControlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentControl
   */
  omit?: Prisma.AssessmentControlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentControlInclude<ExtArgs> | null
}
