
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BehaviorMeasurement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BehaviorMeasurement
 * 
 */
export type BehaviorMeasurementModel = runtime.Types.Result.DefaultSelection<Prisma.$BehaviorMeasurementPayload>

export type AggregateBehaviorMeasurement = {
  _count: BehaviorMeasurementCountAggregateOutputType | null
  _avg: BehaviorMeasurementAvgAggregateOutputType | null
  _sum: BehaviorMeasurementSumAggregateOutputType | null
  _min: BehaviorMeasurementMinAggregateOutputType | null
  _max: BehaviorMeasurementMaxAggregateOutputType | null
}

export type BehaviorMeasurementAvgAggregateOutputType = {
  plansMade: number | null
  controlsTested: number | null
  evidenceDocumented: number | null
  qualityScore: number | null
}

export type BehaviorMeasurementSumAggregateOutputType = {
  plansMade: number | null
  controlsTested: number | null
  evidenceDocumented: number | null
  qualityScore: number | null
}

export type BehaviorMeasurementMinAggregateOutputType = {
  id: string | null
  userId: string | null
  date: Date | null
  plansMade: number | null
  controlsTested: number | null
  evidenceDocumented: number | null
  teamEngagement: boolean | null
  qualityScore: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BehaviorMeasurementMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  date: Date | null
  plansMade: number | null
  controlsTested: number | null
  evidenceDocumented: number | null
  teamEngagement: boolean | null
  qualityScore: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BehaviorMeasurementCountAggregateOutputType = {
  id: number
  userId: number
  date: number
  plansMade: number
  controlsTested: number
  evidenceDocumented: number
  teamEngagement: number
  qualityScore: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BehaviorMeasurementAvgAggregateInputType = {
  plansMade?: true
  controlsTested?: true
  evidenceDocumented?: true
  qualityScore?: true
}

export type BehaviorMeasurementSumAggregateInputType = {
  plansMade?: true
  controlsTested?: true
  evidenceDocumented?: true
  qualityScore?: true
}

export type BehaviorMeasurementMinAggregateInputType = {
  id?: true
  userId?: true
  date?: true
  plansMade?: true
  controlsTested?: true
  evidenceDocumented?: true
  teamEngagement?: true
  qualityScore?: true
  createdAt?: true
  updatedAt?: true
}

export type BehaviorMeasurementMaxAggregateInputType = {
  id?: true
  userId?: true
  date?: true
  plansMade?: true
  controlsTested?: true
  evidenceDocumented?: true
  teamEngagement?: true
  qualityScore?: true
  createdAt?: true
  updatedAt?: true
}

export type BehaviorMeasurementCountAggregateInputType = {
  id?: true
  userId?: true
  date?: true
  plansMade?: true
  controlsTested?: true
  evidenceDocumented?: true
  teamEngagement?: true
  qualityScore?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BehaviorMeasurementAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BehaviorMeasurement to aggregate.
   */
  where?: Prisma.BehaviorMeasurementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BehaviorMeasurements to fetch.
   */
  orderBy?: Prisma.BehaviorMeasurementOrderByWithRelationInput | Prisma.BehaviorMeasurementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BehaviorMeasurementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BehaviorMeasurements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BehaviorMeasurements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BehaviorMeasurements
  **/
  _count?: true | BehaviorMeasurementCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BehaviorMeasurementAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BehaviorMeasurementSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BehaviorMeasurementMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BehaviorMeasurementMaxAggregateInputType
}

export type GetBehaviorMeasurementAggregateType<T extends BehaviorMeasurementAggregateArgs> = {
      [P in keyof T & keyof AggregateBehaviorMeasurement]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBehaviorMeasurement[P]>
    : Prisma.GetScalarType<T[P], AggregateBehaviorMeasurement[P]>
}




export type BehaviorMeasurementGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BehaviorMeasurementWhereInput
  orderBy?: Prisma.BehaviorMeasurementOrderByWithAggregationInput | Prisma.BehaviorMeasurementOrderByWithAggregationInput[]
  by: Prisma.BehaviorMeasurementScalarFieldEnum[] | Prisma.BehaviorMeasurementScalarFieldEnum
  having?: Prisma.BehaviorMeasurementScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BehaviorMeasurementCountAggregateInputType | true
  _avg?: BehaviorMeasurementAvgAggregateInputType
  _sum?: BehaviorMeasurementSumAggregateInputType
  _min?: BehaviorMeasurementMinAggregateInputType
  _max?: BehaviorMeasurementMaxAggregateInputType
}

export type BehaviorMeasurementGroupByOutputType = {
  id: string
  userId: string
  date: Date
  plansMade: number
  controlsTested: number
  evidenceDocumented: number
  teamEngagement: boolean
  qualityScore: number
  createdAt: Date
  updatedAt: Date
  _count: BehaviorMeasurementCountAggregateOutputType | null
  _avg: BehaviorMeasurementAvgAggregateOutputType | null
  _sum: BehaviorMeasurementSumAggregateOutputType | null
  _min: BehaviorMeasurementMinAggregateOutputType | null
  _max: BehaviorMeasurementMaxAggregateOutputType | null
}

export type GetBehaviorMeasurementGroupByPayload<T extends BehaviorMeasurementGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BehaviorMeasurementGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BehaviorMeasurementGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BehaviorMeasurementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BehaviorMeasurementGroupByOutputType[P]>
      }
    >
  >



export type BehaviorMeasurementWhereInput = {
  AND?: Prisma.BehaviorMeasurementWhereInput | Prisma.BehaviorMeasurementWhereInput[]
  OR?: Prisma.BehaviorMeasurementWhereInput[]
  NOT?: Prisma.BehaviorMeasurementWhereInput | Prisma.BehaviorMeasurementWhereInput[]
  id?: Prisma.StringFilter<"BehaviorMeasurement"> | string
  userId?: Prisma.StringFilter<"BehaviorMeasurement"> | string
  date?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
  plansMade?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  controlsTested?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  evidenceDocumented?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  teamEngagement?: Prisma.BoolFilter<"BehaviorMeasurement"> | boolean
  qualityScore?: Prisma.FloatFilter<"BehaviorMeasurement"> | number
  createdAt?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type BehaviorMeasurementOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  plansMade?: Prisma.SortOrder
  controlsTested?: Prisma.SortOrder
  evidenceDocumented?: Prisma.SortOrder
  teamEngagement?: Prisma.SortOrder
  qualityScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type BehaviorMeasurementWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_date?: Prisma.BehaviorMeasurementUserIdDateCompoundUniqueInput
  AND?: Prisma.BehaviorMeasurementWhereInput | Prisma.BehaviorMeasurementWhereInput[]
  OR?: Prisma.BehaviorMeasurementWhereInput[]
  NOT?: Prisma.BehaviorMeasurementWhereInput | Prisma.BehaviorMeasurementWhereInput[]
  userId?: Prisma.StringFilter<"BehaviorMeasurement"> | string
  date?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
  plansMade?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  controlsTested?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  evidenceDocumented?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  teamEngagement?: Prisma.BoolFilter<"BehaviorMeasurement"> | boolean
  qualityScore?: Prisma.FloatFilter<"BehaviorMeasurement"> | number
  createdAt?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_date">

export type BehaviorMeasurementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  plansMade?: Prisma.SortOrder
  controlsTested?: Prisma.SortOrder
  evidenceDocumented?: Prisma.SortOrder
  teamEngagement?: Prisma.SortOrder
  qualityScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BehaviorMeasurementCountOrderByAggregateInput
  _avg?: Prisma.BehaviorMeasurementAvgOrderByAggregateInput
  _max?: Prisma.BehaviorMeasurementMaxOrderByAggregateInput
  _min?: Prisma.BehaviorMeasurementMinOrderByAggregateInput
  _sum?: Prisma.BehaviorMeasurementSumOrderByAggregateInput
}

export type BehaviorMeasurementScalarWhereWithAggregatesInput = {
  AND?: Prisma.BehaviorMeasurementScalarWhereWithAggregatesInput | Prisma.BehaviorMeasurementScalarWhereWithAggregatesInput[]
  OR?: Prisma.BehaviorMeasurementScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BehaviorMeasurementScalarWhereWithAggregatesInput | Prisma.BehaviorMeasurementScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BehaviorMeasurement"> | string
  userId?: Prisma.StringWithAggregatesFilter<"BehaviorMeasurement"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"BehaviorMeasurement"> | Date | string
  plansMade?: Prisma.IntWithAggregatesFilter<"BehaviorMeasurement"> | number
  controlsTested?: Prisma.IntWithAggregatesFilter<"BehaviorMeasurement"> | number
  evidenceDocumented?: Prisma.IntWithAggregatesFilter<"BehaviorMeasurement"> | number
  teamEngagement?: Prisma.BoolWithAggregatesFilter<"BehaviorMeasurement"> | boolean
  qualityScore?: Prisma.FloatWithAggregatesFilter<"BehaviorMeasurement"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BehaviorMeasurement"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BehaviorMeasurement"> | Date | string
}

export type BehaviorMeasurementCreateInput = {
  id?: string
  date: Date | string
  plansMade?: number
  controlsTested?: number
  evidenceDocumented?: number
  teamEngagement?: boolean
  qualityScore?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutBehaviorsInput
}

export type BehaviorMeasurementUncheckedCreateInput = {
  id?: string
  userId: string
  date: Date | string
  plansMade?: number
  controlsTested?: number
  evidenceDocumented?: number
  teamEngagement?: boolean
  qualityScore?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BehaviorMeasurementUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plansMade?: Prisma.IntFieldUpdateOperationsInput | number
  controlsTested?: Prisma.IntFieldUpdateOperationsInput | number
  evidenceDocumented?: Prisma.IntFieldUpdateOperationsInput | number
  teamEngagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  qualityScore?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutBehaviorsNestedInput
}

export type BehaviorMeasurementUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plansMade?: Prisma.IntFieldUpdateOperationsInput | number
  controlsTested?: Prisma.IntFieldUpdateOperationsInput | number
  evidenceDocumented?: Prisma.IntFieldUpdateOperationsInput | number
  teamEngagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  qualityScore?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BehaviorMeasurementCreateManyInput = {
  id?: string
  userId: string
  date: Date | string
  plansMade?: number
  controlsTested?: number
  evidenceDocumented?: number
  teamEngagement?: boolean
  qualityScore?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BehaviorMeasurementUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plansMade?: Prisma.IntFieldUpdateOperationsInput | number
  controlsTested?: Prisma.IntFieldUpdateOperationsInput | number
  evidenceDocumented?: Prisma.IntFieldUpdateOperationsInput | number
  teamEngagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  qualityScore?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BehaviorMeasurementUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plansMade?: Prisma.IntFieldUpdateOperationsInput | number
  controlsTested?: Prisma.IntFieldUpdateOperationsInput | number
  evidenceDocumented?: Prisma.IntFieldUpdateOperationsInput | number
  teamEngagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  qualityScore?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BehaviorMeasurementListRelationFilter = {
  every?: Prisma.BehaviorMeasurementWhereInput
  some?: Prisma.BehaviorMeasurementWhereInput
  none?: Prisma.BehaviorMeasurementWhereInput
}

export type BehaviorMeasurementOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BehaviorMeasurementUserIdDateCompoundUniqueInput = {
  userId: string
  date: Date | string
}

export type BehaviorMeasurementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  plansMade?: Prisma.SortOrder
  controlsTested?: Prisma.SortOrder
  evidenceDocumented?: Prisma.SortOrder
  teamEngagement?: Prisma.SortOrder
  qualityScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BehaviorMeasurementAvgOrderByAggregateInput = {
  plansMade?: Prisma.SortOrder
  controlsTested?: Prisma.SortOrder
  evidenceDocumented?: Prisma.SortOrder
  qualityScore?: Prisma.SortOrder
}

export type BehaviorMeasurementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  plansMade?: Prisma.SortOrder
  controlsTested?: Prisma.SortOrder
  evidenceDocumented?: Prisma.SortOrder
  teamEngagement?: Prisma.SortOrder
  qualityScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BehaviorMeasurementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  plansMade?: Prisma.SortOrder
  controlsTested?: Prisma.SortOrder
  evidenceDocumented?: Prisma.SortOrder
  teamEngagement?: Prisma.SortOrder
  qualityScore?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BehaviorMeasurementSumOrderByAggregateInput = {
  plansMade?: Prisma.SortOrder
  controlsTested?: Prisma.SortOrder
  evidenceDocumented?: Prisma.SortOrder
  qualityScore?: Prisma.SortOrder
}

export type BehaviorMeasurementCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BehaviorMeasurementCreateWithoutUserInput, Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput> | Prisma.BehaviorMeasurementCreateWithoutUserInput[] | Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BehaviorMeasurementCreateOrConnectWithoutUserInput | Prisma.BehaviorMeasurementCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BehaviorMeasurementCreateManyUserInputEnvelope
  connect?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
}

export type BehaviorMeasurementUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BehaviorMeasurementCreateWithoutUserInput, Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput> | Prisma.BehaviorMeasurementCreateWithoutUserInput[] | Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BehaviorMeasurementCreateOrConnectWithoutUserInput | Prisma.BehaviorMeasurementCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BehaviorMeasurementCreateManyUserInputEnvelope
  connect?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
}

export type BehaviorMeasurementUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BehaviorMeasurementCreateWithoutUserInput, Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput> | Prisma.BehaviorMeasurementCreateWithoutUserInput[] | Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BehaviorMeasurementCreateOrConnectWithoutUserInput | Prisma.BehaviorMeasurementCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BehaviorMeasurementUpsertWithWhereUniqueWithoutUserInput | Prisma.BehaviorMeasurementUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BehaviorMeasurementCreateManyUserInputEnvelope
  set?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
  disconnect?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
  delete?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
  connect?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
  update?: Prisma.BehaviorMeasurementUpdateWithWhereUniqueWithoutUserInput | Prisma.BehaviorMeasurementUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BehaviorMeasurementUpdateManyWithWhereWithoutUserInput | Prisma.BehaviorMeasurementUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BehaviorMeasurementScalarWhereInput | Prisma.BehaviorMeasurementScalarWhereInput[]
}

export type BehaviorMeasurementUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BehaviorMeasurementCreateWithoutUserInput, Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput> | Prisma.BehaviorMeasurementCreateWithoutUserInput[] | Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BehaviorMeasurementCreateOrConnectWithoutUserInput | Prisma.BehaviorMeasurementCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BehaviorMeasurementUpsertWithWhereUniqueWithoutUserInput | Prisma.BehaviorMeasurementUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BehaviorMeasurementCreateManyUserInputEnvelope
  set?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
  disconnect?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
  delete?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
  connect?: Prisma.BehaviorMeasurementWhereUniqueInput | Prisma.BehaviorMeasurementWhereUniqueInput[]
  update?: Prisma.BehaviorMeasurementUpdateWithWhereUniqueWithoutUserInput | Prisma.BehaviorMeasurementUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BehaviorMeasurementUpdateManyWithWhereWithoutUserInput | Prisma.BehaviorMeasurementUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BehaviorMeasurementScalarWhereInput | Prisma.BehaviorMeasurementScalarWhereInput[]
}

export type BehaviorMeasurementCreateWithoutUserInput = {
  id?: string
  date: Date | string
  plansMade?: number
  controlsTested?: number
  evidenceDocumented?: number
  teamEngagement?: boolean
  qualityScore?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BehaviorMeasurementUncheckedCreateWithoutUserInput = {
  id?: string
  date: Date | string
  plansMade?: number
  controlsTested?: number
  evidenceDocumented?: number
  teamEngagement?: boolean
  qualityScore?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BehaviorMeasurementCreateOrConnectWithoutUserInput = {
  where: Prisma.BehaviorMeasurementWhereUniqueInput
  create: Prisma.XOR<Prisma.BehaviorMeasurementCreateWithoutUserInput, Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput>
}

export type BehaviorMeasurementCreateManyUserInputEnvelope = {
  data: Prisma.BehaviorMeasurementCreateManyUserInput | Prisma.BehaviorMeasurementCreateManyUserInput[]
}

export type BehaviorMeasurementUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BehaviorMeasurementWhereUniqueInput
  update: Prisma.XOR<Prisma.BehaviorMeasurementUpdateWithoutUserInput, Prisma.BehaviorMeasurementUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BehaviorMeasurementCreateWithoutUserInput, Prisma.BehaviorMeasurementUncheckedCreateWithoutUserInput>
}

export type BehaviorMeasurementUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BehaviorMeasurementWhereUniqueInput
  data: Prisma.XOR<Prisma.BehaviorMeasurementUpdateWithoutUserInput, Prisma.BehaviorMeasurementUncheckedUpdateWithoutUserInput>
}

export type BehaviorMeasurementUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BehaviorMeasurementScalarWhereInput
  data: Prisma.XOR<Prisma.BehaviorMeasurementUpdateManyMutationInput, Prisma.BehaviorMeasurementUncheckedUpdateManyWithoutUserInput>
}

export type BehaviorMeasurementScalarWhereInput = {
  AND?: Prisma.BehaviorMeasurementScalarWhereInput | Prisma.BehaviorMeasurementScalarWhereInput[]
  OR?: Prisma.BehaviorMeasurementScalarWhereInput[]
  NOT?: Prisma.BehaviorMeasurementScalarWhereInput | Prisma.BehaviorMeasurementScalarWhereInput[]
  id?: Prisma.StringFilter<"BehaviorMeasurement"> | string
  userId?: Prisma.StringFilter<"BehaviorMeasurement"> | string
  date?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
  plansMade?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  controlsTested?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  evidenceDocumented?: Prisma.IntFilter<"BehaviorMeasurement"> | number
  teamEngagement?: Prisma.BoolFilter<"BehaviorMeasurement"> | boolean
  qualityScore?: Prisma.FloatFilter<"BehaviorMeasurement"> | number
  createdAt?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BehaviorMeasurement"> | Date | string
}

export type BehaviorMeasurementCreateManyUserInput = {
  id?: string
  date: Date | string
  plansMade?: number
  controlsTested?: number
  evidenceDocumented?: number
  teamEngagement?: boolean
  qualityScore?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BehaviorMeasurementUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plansMade?: Prisma.IntFieldUpdateOperationsInput | number
  controlsTested?: Prisma.IntFieldUpdateOperationsInput | number
  evidenceDocumented?: Prisma.IntFieldUpdateOperationsInput | number
  teamEngagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  qualityScore?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BehaviorMeasurementUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plansMade?: Prisma.IntFieldUpdateOperationsInput | number
  controlsTested?: Prisma.IntFieldUpdateOperationsInput | number
  evidenceDocumented?: Prisma.IntFieldUpdateOperationsInput | number
  teamEngagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  qualityScore?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BehaviorMeasurementUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plansMade?: Prisma.IntFieldUpdateOperationsInput | number
  controlsTested?: Prisma.IntFieldUpdateOperationsInput | number
  evidenceDocumented?: Prisma.IntFieldUpdateOperationsInput | number
  teamEngagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  qualityScore?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BehaviorMeasurementSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  date?: boolean
  plansMade?: boolean
  controlsTested?: boolean
  evidenceDocumented?: boolean
  teamEngagement?: boolean
  qualityScore?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["behaviorMeasurement"]>

export type BehaviorMeasurementSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  date?: boolean
  plansMade?: boolean
  controlsTested?: boolean
  evidenceDocumented?: boolean
  teamEngagement?: boolean
  qualityScore?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["behaviorMeasurement"]>

export type BehaviorMeasurementSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  date?: boolean
  plansMade?: boolean
  controlsTested?: boolean
  evidenceDocumented?: boolean
  teamEngagement?: boolean
  qualityScore?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["behaviorMeasurement"]>

export type BehaviorMeasurementSelectScalar = {
  id?: boolean
  userId?: boolean
  date?: boolean
  plansMade?: boolean
  controlsTested?: boolean
  evidenceDocumented?: boolean
  teamEngagement?: boolean
  qualityScore?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BehaviorMeasurementOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "date" | "plansMade" | "controlsTested" | "evidenceDocumented" | "teamEngagement" | "qualityScore" | "createdAt" | "updatedAt", ExtArgs["result"]["behaviorMeasurement"]>
export type BehaviorMeasurementInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BehaviorMeasurementIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BehaviorMeasurementIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BehaviorMeasurementPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BehaviorMeasurement"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    date: Date
    plansMade: number
    controlsTested: number
    evidenceDocumented: number
    teamEngagement: boolean
    qualityScore: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["behaviorMeasurement"]>
  composites: {}
}

export type BehaviorMeasurementGetPayload<S extends boolean | null | undefined | BehaviorMeasurementDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload, S>

export type BehaviorMeasurementCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BehaviorMeasurementFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BehaviorMeasurementCountAggregateInputType | true
  }

export interface BehaviorMeasurementDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BehaviorMeasurement'], meta: { name: 'BehaviorMeasurement' } }
  /**
   * Find zero or one BehaviorMeasurement that matches the filter.
   * @param {BehaviorMeasurementFindUniqueArgs} args - Arguments to find a BehaviorMeasurement
   * @example
   * // Get one BehaviorMeasurement
   * const behaviorMeasurement = await prisma.behaviorMeasurement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BehaviorMeasurementFindUniqueArgs>(args: Prisma.SelectSubset<T, BehaviorMeasurementFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BehaviorMeasurementClient<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BehaviorMeasurement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BehaviorMeasurementFindUniqueOrThrowArgs} args - Arguments to find a BehaviorMeasurement
   * @example
   * // Get one BehaviorMeasurement
   * const behaviorMeasurement = await prisma.behaviorMeasurement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BehaviorMeasurementFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BehaviorMeasurementFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BehaviorMeasurementClient<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BehaviorMeasurement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BehaviorMeasurementFindFirstArgs} args - Arguments to find a BehaviorMeasurement
   * @example
   * // Get one BehaviorMeasurement
   * const behaviorMeasurement = await prisma.behaviorMeasurement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BehaviorMeasurementFindFirstArgs>(args?: Prisma.SelectSubset<T, BehaviorMeasurementFindFirstArgs<ExtArgs>>): Prisma.Prisma__BehaviorMeasurementClient<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BehaviorMeasurement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BehaviorMeasurementFindFirstOrThrowArgs} args - Arguments to find a BehaviorMeasurement
   * @example
   * // Get one BehaviorMeasurement
   * const behaviorMeasurement = await prisma.behaviorMeasurement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BehaviorMeasurementFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BehaviorMeasurementFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BehaviorMeasurementClient<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BehaviorMeasurements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BehaviorMeasurementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BehaviorMeasurements
   * const behaviorMeasurements = await prisma.behaviorMeasurement.findMany()
   * 
   * // Get first 10 BehaviorMeasurements
   * const behaviorMeasurements = await prisma.behaviorMeasurement.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const behaviorMeasurementWithIdOnly = await prisma.behaviorMeasurement.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BehaviorMeasurementFindManyArgs>(args?: Prisma.SelectSubset<T, BehaviorMeasurementFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BehaviorMeasurement.
   * @param {BehaviorMeasurementCreateArgs} args - Arguments to create a BehaviorMeasurement.
   * @example
   * // Create one BehaviorMeasurement
   * const BehaviorMeasurement = await prisma.behaviorMeasurement.create({
   *   data: {
   *     // ... data to create a BehaviorMeasurement
   *   }
   * })
   * 
   */
  create<T extends BehaviorMeasurementCreateArgs>(args: Prisma.SelectSubset<T, BehaviorMeasurementCreateArgs<ExtArgs>>): Prisma.Prisma__BehaviorMeasurementClient<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BehaviorMeasurements.
   * @param {BehaviorMeasurementCreateManyArgs} args - Arguments to create many BehaviorMeasurements.
   * @example
   * // Create many BehaviorMeasurements
   * const behaviorMeasurement = await prisma.behaviorMeasurement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BehaviorMeasurementCreateManyArgs>(args?: Prisma.SelectSubset<T, BehaviorMeasurementCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BehaviorMeasurements and returns the data saved in the database.
   * @param {BehaviorMeasurementCreateManyAndReturnArgs} args - Arguments to create many BehaviorMeasurements.
   * @example
   * // Create many BehaviorMeasurements
   * const behaviorMeasurement = await prisma.behaviorMeasurement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BehaviorMeasurements and only return the `id`
   * const behaviorMeasurementWithIdOnly = await prisma.behaviorMeasurement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BehaviorMeasurementCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BehaviorMeasurementCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BehaviorMeasurement.
   * @param {BehaviorMeasurementDeleteArgs} args - Arguments to delete one BehaviorMeasurement.
   * @example
   * // Delete one BehaviorMeasurement
   * const BehaviorMeasurement = await prisma.behaviorMeasurement.delete({
   *   where: {
   *     // ... filter to delete one BehaviorMeasurement
   *   }
   * })
   * 
   */
  delete<T extends BehaviorMeasurementDeleteArgs>(args: Prisma.SelectSubset<T, BehaviorMeasurementDeleteArgs<ExtArgs>>): Prisma.Prisma__BehaviorMeasurementClient<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BehaviorMeasurement.
   * @param {BehaviorMeasurementUpdateArgs} args - Arguments to update one BehaviorMeasurement.
   * @example
   * // Update one BehaviorMeasurement
   * const behaviorMeasurement = await prisma.behaviorMeasurement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BehaviorMeasurementUpdateArgs>(args: Prisma.SelectSubset<T, BehaviorMeasurementUpdateArgs<ExtArgs>>): Prisma.Prisma__BehaviorMeasurementClient<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BehaviorMeasurements.
   * @param {BehaviorMeasurementDeleteManyArgs} args - Arguments to filter BehaviorMeasurements to delete.
   * @example
   * // Delete a few BehaviorMeasurements
   * const { count } = await prisma.behaviorMeasurement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BehaviorMeasurementDeleteManyArgs>(args?: Prisma.SelectSubset<T, BehaviorMeasurementDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BehaviorMeasurements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BehaviorMeasurementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BehaviorMeasurements
   * const behaviorMeasurement = await prisma.behaviorMeasurement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BehaviorMeasurementUpdateManyArgs>(args: Prisma.SelectSubset<T, BehaviorMeasurementUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BehaviorMeasurements and returns the data updated in the database.
   * @param {BehaviorMeasurementUpdateManyAndReturnArgs} args - Arguments to update many BehaviorMeasurements.
   * @example
   * // Update many BehaviorMeasurements
   * const behaviorMeasurement = await prisma.behaviorMeasurement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BehaviorMeasurements and only return the `id`
   * const behaviorMeasurementWithIdOnly = await prisma.behaviorMeasurement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BehaviorMeasurementUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BehaviorMeasurementUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BehaviorMeasurement.
   * @param {BehaviorMeasurementUpsertArgs} args - Arguments to update or create a BehaviorMeasurement.
   * @example
   * // Update or create a BehaviorMeasurement
   * const behaviorMeasurement = await prisma.behaviorMeasurement.upsert({
   *   create: {
   *     // ... data to create a BehaviorMeasurement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BehaviorMeasurement we want to update
   *   }
   * })
   */
  upsert<T extends BehaviorMeasurementUpsertArgs>(args: Prisma.SelectSubset<T, BehaviorMeasurementUpsertArgs<ExtArgs>>): Prisma.Prisma__BehaviorMeasurementClient<runtime.Types.Result.GetResult<Prisma.$BehaviorMeasurementPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BehaviorMeasurements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BehaviorMeasurementCountArgs} args - Arguments to filter BehaviorMeasurements to count.
   * @example
   * // Count the number of BehaviorMeasurements
   * const count = await prisma.behaviorMeasurement.count({
   *   where: {
   *     // ... the filter for the BehaviorMeasurements we want to count
   *   }
   * })
  **/
  count<T extends BehaviorMeasurementCountArgs>(
    args?: Prisma.Subset<T, BehaviorMeasurementCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BehaviorMeasurementCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BehaviorMeasurement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BehaviorMeasurementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BehaviorMeasurementAggregateArgs>(args: Prisma.Subset<T, BehaviorMeasurementAggregateArgs>): Prisma.PrismaPromise<GetBehaviorMeasurementAggregateType<T>>

  /**
   * Group by BehaviorMeasurement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BehaviorMeasurementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BehaviorMeasurementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BehaviorMeasurementGroupByArgs['orderBy'] }
      : { orderBy?: BehaviorMeasurementGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BehaviorMeasurementGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBehaviorMeasurementGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BehaviorMeasurement model
 */
readonly fields: BehaviorMeasurementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BehaviorMeasurement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BehaviorMeasurementClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BehaviorMeasurement model
 */
export interface BehaviorMeasurementFieldRefs {
  readonly id: Prisma.FieldRef<"BehaviorMeasurement", 'String'>
  readonly userId: Prisma.FieldRef<"BehaviorMeasurement", 'String'>
  readonly date: Prisma.FieldRef<"BehaviorMeasurement", 'DateTime'>
  readonly plansMade: Prisma.FieldRef<"BehaviorMeasurement", 'Int'>
  readonly controlsTested: Prisma.FieldRef<"BehaviorMeasurement", 'Int'>
  readonly evidenceDocumented: Prisma.FieldRef<"BehaviorMeasurement", 'Int'>
  readonly teamEngagement: Prisma.FieldRef<"BehaviorMeasurement", 'Boolean'>
  readonly qualityScore: Prisma.FieldRef<"BehaviorMeasurement", 'Float'>
  readonly createdAt: Prisma.FieldRef<"BehaviorMeasurement", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BehaviorMeasurement", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BehaviorMeasurement findUnique
 */
export type BehaviorMeasurementFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * Filter, which BehaviorMeasurement to fetch.
   */
  where: Prisma.BehaviorMeasurementWhereUniqueInput
}

/**
 * BehaviorMeasurement findUniqueOrThrow
 */
export type BehaviorMeasurementFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * Filter, which BehaviorMeasurement to fetch.
   */
  where: Prisma.BehaviorMeasurementWhereUniqueInput
}

/**
 * BehaviorMeasurement findFirst
 */
export type BehaviorMeasurementFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * Filter, which BehaviorMeasurement to fetch.
   */
  where?: Prisma.BehaviorMeasurementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BehaviorMeasurements to fetch.
   */
  orderBy?: Prisma.BehaviorMeasurementOrderByWithRelationInput | Prisma.BehaviorMeasurementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BehaviorMeasurements.
   */
  cursor?: Prisma.BehaviorMeasurementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BehaviorMeasurements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BehaviorMeasurements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BehaviorMeasurements.
   */
  distinct?: Prisma.BehaviorMeasurementScalarFieldEnum | Prisma.BehaviorMeasurementScalarFieldEnum[]
}

/**
 * BehaviorMeasurement findFirstOrThrow
 */
export type BehaviorMeasurementFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * Filter, which BehaviorMeasurement to fetch.
   */
  where?: Prisma.BehaviorMeasurementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BehaviorMeasurements to fetch.
   */
  orderBy?: Prisma.BehaviorMeasurementOrderByWithRelationInput | Prisma.BehaviorMeasurementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BehaviorMeasurements.
   */
  cursor?: Prisma.BehaviorMeasurementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BehaviorMeasurements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BehaviorMeasurements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BehaviorMeasurements.
   */
  distinct?: Prisma.BehaviorMeasurementScalarFieldEnum | Prisma.BehaviorMeasurementScalarFieldEnum[]
}

/**
 * BehaviorMeasurement findMany
 */
export type BehaviorMeasurementFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * Filter, which BehaviorMeasurements to fetch.
   */
  where?: Prisma.BehaviorMeasurementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BehaviorMeasurements to fetch.
   */
  orderBy?: Prisma.BehaviorMeasurementOrderByWithRelationInput | Prisma.BehaviorMeasurementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BehaviorMeasurements.
   */
  cursor?: Prisma.BehaviorMeasurementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BehaviorMeasurements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BehaviorMeasurements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BehaviorMeasurements.
   */
  distinct?: Prisma.BehaviorMeasurementScalarFieldEnum | Prisma.BehaviorMeasurementScalarFieldEnum[]
}

/**
 * BehaviorMeasurement create
 */
export type BehaviorMeasurementCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * The data needed to create a BehaviorMeasurement.
   */
  data: Prisma.XOR<Prisma.BehaviorMeasurementCreateInput, Prisma.BehaviorMeasurementUncheckedCreateInput>
}

/**
 * BehaviorMeasurement createMany
 */
export type BehaviorMeasurementCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BehaviorMeasurements.
   */
  data: Prisma.BehaviorMeasurementCreateManyInput | Prisma.BehaviorMeasurementCreateManyInput[]
}

/**
 * BehaviorMeasurement createManyAndReturn
 */
export type BehaviorMeasurementCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * The data used to create many BehaviorMeasurements.
   */
  data: Prisma.BehaviorMeasurementCreateManyInput | Prisma.BehaviorMeasurementCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BehaviorMeasurement update
 */
export type BehaviorMeasurementUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * The data needed to update a BehaviorMeasurement.
   */
  data: Prisma.XOR<Prisma.BehaviorMeasurementUpdateInput, Prisma.BehaviorMeasurementUncheckedUpdateInput>
  /**
   * Choose, which BehaviorMeasurement to update.
   */
  where: Prisma.BehaviorMeasurementWhereUniqueInput
}

/**
 * BehaviorMeasurement updateMany
 */
export type BehaviorMeasurementUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BehaviorMeasurements.
   */
  data: Prisma.XOR<Prisma.BehaviorMeasurementUpdateManyMutationInput, Prisma.BehaviorMeasurementUncheckedUpdateManyInput>
  /**
   * Filter which BehaviorMeasurements to update
   */
  where?: Prisma.BehaviorMeasurementWhereInput
  /**
   * Limit how many BehaviorMeasurements to update.
   */
  limit?: number
}

/**
 * BehaviorMeasurement updateManyAndReturn
 */
export type BehaviorMeasurementUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * The data used to update BehaviorMeasurements.
   */
  data: Prisma.XOR<Prisma.BehaviorMeasurementUpdateManyMutationInput, Prisma.BehaviorMeasurementUncheckedUpdateManyInput>
  /**
   * Filter which BehaviorMeasurements to update
   */
  where?: Prisma.BehaviorMeasurementWhereInput
  /**
   * Limit how many BehaviorMeasurements to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BehaviorMeasurement upsert
 */
export type BehaviorMeasurementUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * The filter to search for the BehaviorMeasurement to update in case it exists.
   */
  where: Prisma.BehaviorMeasurementWhereUniqueInput
  /**
   * In case the BehaviorMeasurement found by the `where` argument doesn't exist, create a new BehaviorMeasurement with this data.
   */
  create: Prisma.XOR<Prisma.BehaviorMeasurementCreateInput, Prisma.BehaviorMeasurementUncheckedCreateInput>
  /**
   * In case the BehaviorMeasurement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BehaviorMeasurementUpdateInput, Prisma.BehaviorMeasurementUncheckedUpdateInput>
}

/**
 * BehaviorMeasurement delete
 */
export type BehaviorMeasurementDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
  /**
   * Filter which BehaviorMeasurement to delete.
   */
  where: Prisma.BehaviorMeasurementWhereUniqueInput
}

/**
 * BehaviorMeasurement deleteMany
 */
export type BehaviorMeasurementDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BehaviorMeasurements to delete
   */
  where?: Prisma.BehaviorMeasurementWhereInput
  /**
   * Limit how many BehaviorMeasurements to delete.
   */
  limit?: number
}

/**
 * BehaviorMeasurement without action
 */
export type BehaviorMeasurementDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BehaviorMeasurement
   */
  select?: Prisma.BehaviorMeasurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BehaviorMeasurement
   */
  omit?: Prisma.BehaviorMeasurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BehaviorMeasurementInclude<ExtArgs> | null
}
