
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model AssuranceActivityType
 * 
 */
export type AssuranceActivityType = Prisma.AssuranceActivityTypeModel
/**
 * Model ProcessArea
 * 
 */
export type ProcessArea = Prisma.ProcessAreaModel
/**
 * Model SubProcess
 * 
 */
export type SubProcess = Prisma.SubProcessModel
/**
 * Model Control
 * 
 */
export type Control = Prisma.ControlModel
/**
 * Model AssessmentTemplate
 * 
 */
export type AssessmentTemplate = Prisma.AssessmentTemplateModel
/**
 * Model AssessmentTemplateControlLinkage
 * 
 */
export type AssessmentTemplateControlLinkage = Prisma.AssessmentTemplateControlLinkageModel
/**
 * Model AssessmentTemplateActivityType
 * 
 */
export type AssessmentTemplateActivityType = Prisma.AssessmentTemplateActivityTypeModel
/**
 * Model Assessment
 * 
 */
export type Assessment = Prisma.AssessmentModel
/**
 * Model AssessmentControl
 * 
 */
export type AssessmentControl = Prisma.AssessmentControlModel
/**
 * Model SampleType
 * 
 */
export type SampleType = Prisma.SampleTypeModel
/**
 * Model RecordSourceType
 * 
 */
export type RecordSourceType = Prisma.RecordSourceTypeModel
/**
 * Model Sample
 * 
 */
export type Sample = Prisma.SampleModel
/**
 * Model AchievementBadge
 * 
 */
export type AchievementBadge = Prisma.AchievementBadgeModel
/**
 * Model UserAchievement
 * 
 */
export type UserAchievement = Prisma.UserAchievementModel
/**
 * Model PointTransaction
 * 
 */
export type PointTransaction = Prisma.PointTransactionModel
/**
 * Model BehaviorMeasurement
 * 
 */
export type BehaviorMeasurement = Prisma.BehaviorMeasurementModel
/**
 * Model EmotionalDriveMetric
 * 
 */
export type EmotionalDriveMetric = Prisma.EmotionalDriveMetricModel
/**
 * Model Milestone
 * 
 */
export type Milestone = Prisma.MilestoneModel
