
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model AssuranceActivityType
 * 
 */
export type AssuranceActivityType = Prisma.AssuranceActivityTypeModel
/**
 * Model ProcessArea
 * 
 */
export type ProcessArea = Prisma.ProcessAreaModel
/**
 * Model SubProcess
 * 
 */
export type SubProcess = Prisma.SubProcessModel
/**
 * Model Control
 * 
 */
export type Control = Prisma.ControlModel
/**
 * Model AssessmentTemplate
 * 
 */
export type AssessmentTemplate = Prisma.AssessmentTemplateModel
/**
 * Model AssessmentTemplateControlLinkage
 * 
 */
export type AssessmentTemplateControlLinkage = Prisma.AssessmentTemplateControlLinkageModel
/**
 * Model AssessmentTemplateActivityType
 * 
 */
export type AssessmentTemplateActivityType = Prisma.AssessmentTemplateActivityTypeModel
/**
 * Model Assessment
 * 
 */
export type Assessment = Prisma.AssessmentModel
/**
 * Model AssessmentControl
 * 
 */
export type AssessmentControl = Prisma.AssessmentControlModel
/**
 * Model SampleType
 * 
 */
export type SampleType = Prisma.SampleTypeModel
/**
 * Model RecordSourceType
 * 
 */
export type RecordSourceType = Prisma.RecordSourceTypeModel
/**
 * Model Sample
 * 
 */
export type Sample = Prisma.SampleModel
/**
 * Model AchievementBadge
 * 
 */
export type AchievementBadge = Prisma.AchievementBadgeModel
/**
 * Model UserAchievement
 * 
 */
export type UserAchievement = Prisma.UserAchievementModel
/**
 * Model PointTransaction
 * 
 */
export type PointTransaction = Prisma.PointTransactionModel
/**
 * Model BehaviorMeasurement
 * 
 */
export type BehaviorMeasurement = Prisma.BehaviorMeasurementModel
/**
 * Model EmotionalDriveMetric
 * 
 */
export type EmotionalDriveMetric = Prisma.EmotionalDriveMetricModel
/**
 * Model Milestone
 * 
 */
export type Milestone = Prisma.MilestoneModel
