
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type EnumRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[]
  notIn?: $Enums.Role[]
  not?: Prisma.NestedEnumRoleFilter<$PrismaModel> | $Enums.Role
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[]
  notIn?: $Enums.Role[]
  not?: Prisma.NestedEnumRoleWithAggregatesFilter<$PrismaModel> | $Enums.Role
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumRoleFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type EnumLOAFilter<$PrismaModel = never> = {
  equals?: $Enums.LOA | Prisma.EnumLOAFieldRefInput<$PrismaModel>
  in?: $Enums.LOA[]
  notIn?: $Enums.LOA[]
  not?: Prisma.NestedEnumLOAFilter<$PrismaModel> | $Enums.LOA
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type EnumLOAWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LOA | Prisma.EnumLOAFieldRefInput<$PrismaModel>
  in?: $Enums.LOA[]
  notIn?: $Enums.LOA[]
  not?: Prisma.NestedEnumLOAWithAggregatesFilter<$PrismaModel> | $Enums.LOA
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLOAFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLOAFilter<$PrismaModel>
}

export type EnumControlTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.ControlType | Prisma.EnumControlTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ControlType[]
  notIn?: $Enums.ControlType[]
  not?: Prisma.NestedEnumControlTypeFilter<$PrismaModel> | $Enums.ControlType
}

export type EnumControlTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ControlType | Prisma.EnumControlTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ControlType[]
  notIn?: $Enums.ControlType[]
  not?: Prisma.NestedEnumControlTypeWithAggregatesFilter<$PrismaModel> | $Enums.ControlType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumControlTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumControlTypeFilter<$PrismaModel>
}

export type EnumAssessmentStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.AssessmentStatus | Prisma.EnumAssessmentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AssessmentStatus[]
  notIn?: $Enums.AssessmentStatus[]
  not?: Prisma.NestedEnumAssessmentStatusFilter<$PrismaModel> | $Enums.AssessmentStatus
}

export type EnumAssessmentStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AssessmentStatus | Prisma.EnumAssessmentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AssessmentStatus[]
  notIn?: $Enums.AssessmentStatus[]
  not?: Prisma.NestedEnumAssessmentStatusWithAggregatesFilter<$PrismaModel> | $Enums.AssessmentStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAssessmentStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAssessmentStatusFilter<$PrismaModel>
}

export type EnumSampleStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.SampleStatus | Prisma.EnumSampleStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SampleStatus[]
  notIn?: $Enums.SampleStatus[]
  not?: Prisma.NestedEnumSampleStatusFilter<$PrismaModel> | $Enums.SampleStatus
}

export type EnumSampleConclusionNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.SampleConclusion | Prisma.EnumSampleConclusionFieldRefInput<$PrismaModel> | null
  in?: $Enums.SampleConclusion[] | null
  notIn?: $Enums.SampleConclusion[] | null
  not?: Prisma.NestedEnumSampleConclusionNullableFilter<$PrismaModel> | $Enums.SampleConclusion | null
}

export type EnumSampleStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SampleStatus | Prisma.EnumSampleStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SampleStatus[]
  notIn?: $Enums.SampleStatus[]
  not?: Prisma.NestedEnumSampleStatusWithAggregatesFilter<$PrismaModel> | $Enums.SampleStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSampleStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSampleStatusFilter<$PrismaModel>
}

export type EnumSampleConclusionNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SampleConclusion | Prisma.EnumSampleConclusionFieldRefInput<$PrismaModel> | null
  in?: $Enums.SampleConclusion[] | null
  notIn?: $Enums.SampleConclusion[] | null
  not?: Prisma.NestedEnumSampleConclusionNullableWithAggregatesFilter<$PrismaModel> | $Enums.SampleConclusion | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSampleConclusionNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSampleConclusionNullableFilter<$PrismaModel>
}

export type EnumEmotionalDriveFilter<$PrismaModel = never> = {
  equals?: $Enums.EmotionalDrive | Prisma.EnumEmotionalDriveFieldRefInput<$PrismaModel>
  in?: $Enums.EmotionalDrive[]
  notIn?: $Enums.EmotionalDrive[]
  not?: Prisma.NestedEnumEmotionalDriveFilter<$PrismaModel> | $Enums.EmotionalDrive
}

export type EnumBadgeRarityFilter<$PrismaModel = never> = {
  equals?: $Enums.BadgeRarity | Prisma.EnumBadgeRarityFieldRefInput<$PrismaModel>
  in?: $Enums.BadgeRarity[]
  notIn?: $Enums.BadgeRarity[]
  not?: Prisma.NestedEnumBadgeRarityFilter<$PrismaModel> | $Enums.BadgeRarity
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type EnumEmotionalDriveWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmotionalDrive | Prisma.EnumEmotionalDriveFieldRefInput<$PrismaModel>
  in?: $Enums.EmotionalDrive[]
  notIn?: $Enums.EmotionalDrive[]
  not?: Prisma.NestedEnumEmotionalDriveWithAggregatesFilter<$PrismaModel> | $Enums.EmotionalDrive
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmotionalDriveFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmotionalDriveFilter<$PrismaModel>
}

export type EnumBadgeRarityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.BadgeRarity | Prisma.EnumBadgeRarityFieldRefInput<$PrismaModel>
  in?: $Enums.BadgeRarity[]
  notIn?: $Enums.BadgeRarity[]
  not?: Prisma.NestedEnumBadgeRarityWithAggregatesFilter<$PrismaModel> | $Enums.BadgeRarity
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumBadgeRarityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumBadgeRarityFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type EnumEmotionalDriveNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.EmotionalDrive | Prisma.EnumEmotionalDriveFieldRefInput<$PrismaModel> | null
  in?: $Enums.EmotionalDrive[] | null
  notIn?: $Enums.EmotionalDrive[] | null
  not?: Prisma.NestedEnumEmotionalDriveNullableFilter<$PrismaModel> | $Enums.EmotionalDrive | null
}

export type FloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type EnumEmotionalDriveNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmotionalDrive | Prisma.EnumEmotionalDriveFieldRefInput<$PrismaModel> | null
  in?: $Enums.EmotionalDrive[] | null
  notIn?: $Enums.EmotionalDrive[] | null
  not?: Prisma.NestedEnumEmotionalDriveNullableWithAggregatesFilter<$PrismaModel> | $Enums.EmotionalDrive | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmotionalDriveNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmotionalDriveNullableFilter<$PrismaModel>
}

export type FloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedEnumRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[]
  notIn?: $Enums.Role[]
  not?: Prisma.NestedEnumRoleFilter<$PrismaModel> | $Enums.Role
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedEnumRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[]
  notIn?: $Enums.Role[]
  not?: Prisma.NestedEnumRoleWithAggregatesFilter<$PrismaModel> | $Enums.Role
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumRoleFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedEnumLOAFilter<$PrismaModel = never> = {
  equals?: $Enums.LOA | Prisma.EnumLOAFieldRefInput<$PrismaModel>
  in?: $Enums.LOA[]
  notIn?: $Enums.LOA[]
  not?: Prisma.NestedEnumLOAFilter<$PrismaModel> | $Enums.LOA
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedEnumLOAWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LOA | Prisma.EnumLOAFieldRefInput<$PrismaModel>
  in?: $Enums.LOA[]
  notIn?: $Enums.LOA[]
  not?: Prisma.NestedEnumLOAWithAggregatesFilter<$PrismaModel> | $Enums.LOA
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLOAFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLOAFilter<$PrismaModel>
}

export type NestedEnumControlTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.ControlType | Prisma.EnumControlTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ControlType[]
  notIn?: $Enums.ControlType[]
  not?: Prisma.NestedEnumControlTypeFilter<$PrismaModel> | $Enums.ControlType
}

export type NestedEnumControlTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ControlType | Prisma.EnumControlTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ControlType[]
  notIn?: $Enums.ControlType[]
  not?: Prisma.NestedEnumControlTypeWithAggregatesFilter<$PrismaModel> | $Enums.ControlType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumControlTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumControlTypeFilter<$PrismaModel>
}

export type NestedEnumAssessmentStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.AssessmentStatus | Prisma.EnumAssessmentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AssessmentStatus[]
  notIn?: $Enums.AssessmentStatus[]
  not?: Prisma.NestedEnumAssessmentStatusFilter<$PrismaModel> | $Enums.AssessmentStatus
}

export type NestedEnumAssessmentStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AssessmentStatus | Prisma.EnumAssessmentStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AssessmentStatus[]
  notIn?: $Enums.AssessmentStatus[]
  not?: Prisma.NestedEnumAssessmentStatusWithAggregatesFilter<$PrismaModel> | $Enums.AssessmentStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAssessmentStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAssessmentStatusFilter<$PrismaModel>
}

export type NestedEnumSampleStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.SampleStatus | Prisma.EnumSampleStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SampleStatus[]
  notIn?: $Enums.SampleStatus[]
  not?: Prisma.NestedEnumSampleStatusFilter<$PrismaModel> | $Enums.SampleStatus
}

export type NestedEnumSampleConclusionNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.SampleConclusion | Prisma.EnumSampleConclusionFieldRefInput<$PrismaModel> | null
  in?: $Enums.SampleConclusion[] | null
  notIn?: $Enums.SampleConclusion[] | null
  not?: Prisma.NestedEnumSampleConclusionNullableFilter<$PrismaModel> | $Enums.SampleConclusion | null
}

export type NestedEnumSampleStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SampleStatus | Prisma.EnumSampleStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SampleStatus[]
  notIn?: $Enums.SampleStatus[]
  not?: Prisma.NestedEnumSampleStatusWithAggregatesFilter<$PrismaModel> | $Enums.SampleStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSampleStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSampleStatusFilter<$PrismaModel>
}

export type NestedEnumSampleConclusionNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SampleConclusion | Prisma.EnumSampleConclusionFieldRefInput<$PrismaModel> | null
  in?: $Enums.SampleConclusion[] | null
  notIn?: $Enums.SampleConclusion[] | null
  not?: Prisma.NestedEnumSampleConclusionNullableWithAggregatesFilter<$PrismaModel> | $Enums.SampleConclusion | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSampleConclusionNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSampleConclusionNullableFilter<$PrismaModel>
}

export type NestedEnumEmotionalDriveFilter<$PrismaModel = never> = {
  equals?: $Enums.EmotionalDrive | Prisma.EnumEmotionalDriveFieldRefInput<$PrismaModel>
  in?: $Enums.EmotionalDrive[]
  notIn?: $Enums.EmotionalDrive[]
  not?: Prisma.NestedEnumEmotionalDriveFilter<$PrismaModel> | $Enums.EmotionalDrive
}

export type NestedEnumBadgeRarityFilter<$PrismaModel = never> = {
  equals?: $Enums.BadgeRarity | Prisma.EnumBadgeRarityFieldRefInput<$PrismaModel>
  in?: $Enums.BadgeRarity[]
  notIn?: $Enums.BadgeRarity[]
  not?: Prisma.NestedEnumBadgeRarityFilter<$PrismaModel> | $Enums.BadgeRarity
}

export type NestedEnumEmotionalDriveWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmotionalDrive | Prisma.EnumEmotionalDriveFieldRefInput<$PrismaModel>
  in?: $Enums.EmotionalDrive[]
  notIn?: $Enums.EmotionalDrive[]
  not?: Prisma.NestedEnumEmotionalDriveWithAggregatesFilter<$PrismaModel> | $Enums.EmotionalDrive
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmotionalDriveFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmotionalDriveFilter<$PrismaModel>
}

export type NestedEnumBadgeRarityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.BadgeRarity | Prisma.EnumBadgeRarityFieldRefInput<$PrismaModel>
  in?: $Enums.BadgeRarity[]
  notIn?: $Enums.BadgeRarity[]
  not?: Prisma.NestedEnumBadgeRarityWithAggregatesFilter<$PrismaModel> | $Enums.BadgeRarity
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumBadgeRarityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumBadgeRarityFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumEmotionalDriveNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.EmotionalDrive | Prisma.EnumEmotionalDriveFieldRefInput<$PrismaModel> | null
  in?: $Enums.EmotionalDrive[] | null
  notIn?: $Enums.EmotionalDrive[] | null
  not?: Prisma.NestedEnumEmotionalDriveNullableFilter<$PrismaModel> | $Enums.EmotionalDrive | null
}

export type NestedEnumEmotionalDriveNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmotionalDrive | Prisma.EnumEmotionalDriveFieldRefInput<$PrismaModel> | null
  in?: $Enums.EmotionalDrive[] | null
  notIn?: $Enums.EmotionalDrive[] | null
  not?: Prisma.NestedEnumEmotionalDriveNullableWithAggregatesFilter<$PrismaModel> | $Enums.EmotionalDrive | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmotionalDriveNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmotionalDriveNullableFilter<$PrismaModel>
}

export type NestedFloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}


