
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  AssuranceActivityType: 'AssuranceActivityType',
  ProcessArea: 'ProcessArea',
  SubProcess: 'SubProcess',
  Control: 'Control',
  AssessmentTemplate: 'AssessmentTemplate',
  AssessmentTemplateControlLinkage: 'AssessmentTemplateControlLinkage',
  AssessmentTemplateActivityType: 'AssessmentTemplateActivityType',
  Assessment: 'Assessment',
  AssessmentControl: 'AssessmentControl',
  SampleType: 'SampleType',
  RecordSourceType: 'RecordSourceType',
  Sample: 'Sample',
  AchievementBadge: 'AchievementBadge',
  UserAchievement: 'UserAchievement',
  PointTransaction: 'PointTransaction',
  BehaviorMeasurement: 'BehaviorMeasurement',
  EmotionalDriveMetric: 'EmotionalDriveMetric',
  Milestone: 'Milestone'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "assuranceActivityType" | "processArea" | "subProcess" | "control" | "assessmentTemplate" | "assessmentTemplateControlLinkage" | "assessmentTemplateActivityType" | "assessment" | "assessmentControl" | "sampleType" | "recordSourceType" | "sample" | "achievementBadge" | "userAchievement" | "pointTransaction" | "behaviorMeasurement" | "emotionalDriveMetric" | "milestone"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    AssuranceActivityType: {
      payload: Prisma.$AssuranceActivityTypePayload<ExtArgs>
      fields: Prisma.AssuranceActivityTypeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AssuranceActivityTypeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AssuranceActivityTypeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>
        }
        findFirst: {
          args: Prisma.AssuranceActivityTypeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AssuranceActivityTypeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>
        }
        findMany: {
          args: Prisma.AssuranceActivityTypeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>[]
        }
        create: {
          args: Prisma.AssuranceActivityTypeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>
        }
        createMany: {
          args: Prisma.AssuranceActivityTypeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AssuranceActivityTypeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>[]
        }
        delete: {
          args: Prisma.AssuranceActivityTypeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>
        }
        update: {
          args: Prisma.AssuranceActivityTypeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>
        }
        deleteMany: {
          args: Prisma.AssuranceActivityTypeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AssuranceActivityTypeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AssuranceActivityTypeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>[]
        }
        upsert: {
          args: Prisma.AssuranceActivityTypeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssuranceActivityTypePayload>
        }
        aggregate: {
          args: Prisma.AssuranceActivityTypeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAssuranceActivityType>
        }
        groupBy: {
          args: Prisma.AssuranceActivityTypeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssuranceActivityTypeGroupByOutputType>[]
        }
        count: {
          args: Prisma.AssuranceActivityTypeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssuranceActivityTypeCountAggregateOutputType> | number
        }
      }
    }
    ProcessArea: {
      payload: Prisma.$ProcessAreaPayload<ExtArgs>
      fields: Prisma.ProcessAreaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProcessAreaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProcessAreaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>
        }
        findFirst: {
          args: Prisma.ProcessAreaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProcessAreaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>
        }
        findMany: {
          args: Prisma.ProcessAreaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>[]
        }
        create: {
          args: Prisma.ProcessAreaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>
        }
        createMany: {
          args: Prisma.ProcessAreaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProcessAreaCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>[]
        }
        delete: {
          args: Prisma.ProcessAreaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>
        }
        update: {
          args: Prisma.ProcessAreaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>
        }
        deleteMany: {
          args: Prisma.ProcessAreaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProcessAreaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProcessAreaUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>[]
        }
        upsert: {
          args: Prisma.ProcessAreaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProcessAreaPayload>
        }
        aggregate: {
          args: Prisma.ProcessAreaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProcessArea>
        }
        groupBy: {
          args: Prisma.ProcessAreaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProcessAreaGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProcessAreaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProcessAreaCountAggregateOutputType> | number
        }
      }
    }
    SubProcess: {
      payload: Prisma.$SubProcessPayload<ExtArgs>
      fields: Prisma.SubProcessFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SubProcessFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SubProcessFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>
        }
        findFirst: {
          args: Prisma.SubProcessFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SubProcessFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>
        }
        findMany: {
          args: Prisma.SubProcessFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>[]
        }
        create: {
          args: Prisma.SubProcessCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>
        }
        createMany: {
          args: Prisma.SubProcessCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SubProcessCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>[]
        }
        delete: {
          args: Prisma.SubProcessDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>
        }
        update: {
          args: Prisma.SubProcessUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>
        }
        deleteMany: {
          args: Prisma.SubProcessDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SubProcessUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SubProcessUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>[]
        }
        upsert: {
          args: Prisma.SubProcessUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SubProcessPayload>
        }
        aggregate: {
          args: Prisma.SubProcessAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSubProcess>
        }
        groupBy: {
          args: Prisma.SubProcessGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SubProcessGroupByOutputType>[]
        }
        count: {
          args: Prisma.SubProcessCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SubProcessCountAggregateOutputType> | number
        }
      }
    }
    Control: {
      payload: Prisma.$ControlPayload<ExtArgs>
      fields: Prisma.ControlFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ControlFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ControlFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>
        }
        findFirst: {
          args: Prisma.ControlFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ControlFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>
        }
        findMany: {
          args: Prisma.ControlFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>[]
        }
        create: {
          args: Prisma.ControlCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>
        }
        createMany: {
          args: Prisma.ControlCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ControlCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>[]
        }
        delete: {
          args: Prisma.ControlDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>
        }
        update: {
          args: Prisma.ControlUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>
        }
        deleteMany: {
          args: Prisma.ControlDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ControlUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ControlUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>[]
        }
        upsert: {
          args: Prisma.ControlUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ControlPayload>
        }
        aggregate: {
          args: Prisma.ControlAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateControl>
        }
        groupBy: {
          args: Prisma.ControlGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ControlGroupByOutputType>[]
        }
        count: {
          args: Prisma.ControlCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ControlCountAggregateOutputType> | number
        }
      }
    }
    AssessmentTemplate: {
      payload: Prisma.$AssessmentTemplatePayload<ExtArgs>
      fields: Prisma.AssessmentTemplateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AssessmentTemplateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AssessmentTemplateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>
        }
        findFirst: {
          args: Prisma.AssessmentTemplateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AssessmentTemplateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>
        }
        findMany: {
          args: Prisma.AssessmentTemplateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>[]
        }
        create: {
          args: Prisma.AssessmentTemplateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>
        }
        createMany: {
          args: Prisma.AssessmentTemplateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AssessmentTemplateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>[]
        }
        delete: {
          args: Prisma.AssessmentTemplateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>
        }
        update: {
          args: Prisma.AssessmentTemplateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>
        }
        deleteMany: {
          args: Prisma.AssessmentTemplateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AssessmentTemplateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AssessmentTemplateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>[]
        }
        upsert: {
          args: Prisma.AssessmentTemplateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplatePayload>
        }
        aggregate: {
          args: Prisma.AssessmentTemplateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAssessmentTemplate>
        }
        groupBy: {
          args: Prisma.AssessmentTemplateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentTemplateGroupByOutputType>[]
        }
        count: {
          args: Prisma.AssessmentTemplateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentTemplateCountAggregateOutputType> | number
        }
      }
    }
    AssessmentTemplateControlLinkage: {
      payload: Prisma.$AssessmentTemplateControlLinkagePayload<ExtArgs>
      fields: Prisma.AssessmentTemplateControlLinkageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AssessmentTemplateControlLinkageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AssessmentTemplateControlLinkageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>
        }
        findFirst: {
          args: Prisma.AssessmentTemplateControlLinkageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AssessmentTemplateControlLinkageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>
        }
        findMany: {
          args: Prisma.AssessmentTemplateControlLinkageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>[]
        }
        create: {
          args: Prisma.AssessmentTemplateControlLinkageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>
        }
        createMany: {
          args: Prisma.AssessmentTemplateControlLinkageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AssessmentTemplateControlLinkageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>[]
        }
        delete: {
          args: Prisma.AssessmentTemplateControlLinkageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>
        }
        update: {
          args: Prisma.AssessmentTemplateControlLinkageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>
        }
        deleteMany: {
          args: Prisma.AssessmentTemplateControlLinkageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AssessmentTemplateControlLinkageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AssessmentTemplateControlLinkageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>[]
        }
        upsert: {
          args: Prisma.AssessmentTemplateControlLinkageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateControlLinkagePayload>
        }
        aggregate: {
          args: Prisma.AssessmentTemplateControlLinkageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAssessmentTemplateControlLinkage>
        }
        groupBy: {
          args: Prisma.AssessmentTemplateControlLinkageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentTemplateControlLinkageGroupByOutputType>[]
        }
        count: {
          args: Prisma.AssessmentTemplateControlLinkageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentTemplateControlLinkageCountAggregateOutputType> | number
        }
      }
    }
    AssessmentTemplateActivityType: {
      payload: Prisma.$AssessmentTemplateActivityTypePayload<ExtArgs>
      fields: Prisma.AssessmentTemplateActivityTypeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AssessmentTemplateActivityTypeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AssessmentTemplateActivityTypeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>
        }
        findFirst: {
          args: Prisma.AssessmentTemplateActivityTypeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AssessmentTemplateActivityTypeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>
        }
        findMany: {
          args: Prisma.AssessmentTemplateActivityTypeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>[]
        }
        create: {
          args: Prisma.AssessmentTemplateActivityTypeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>
        }
        createMany: {
          args: Prisma.AssessmentTemplateActivityTypeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AssessmentTemplateActivityTypeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>[]
        }
        delete: {
          args: Prisma.AssessmentTemplateActivityTypeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>
        }
        update: {
          args: Prisma.AssessmentTemplateActivityTypeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>
        }
        deleteMany: {
          args: Prisma.AssessmentTemplateActivityTypeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AssessmentTemplateActivityTypeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AssessmentTemplateActivityTypeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>[]
        }
        upsert: {
          args: Prisma.AssessmentTemplateActivityTypeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentTemplateActivityTypePayload>
        }
        aggregate: {
          args: Prisma.AssessmentTemplateActivityTypeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAssessmentTemplateActivityType>
        }
        groupBy: {
          args: Prisma.AssessmentTemplateActivityTypeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentTemplateActivityTypeGroupByOutputType>[]
        }
        count: {
          args: Prisma.AssessmentTemplateActivityTypeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentTemplateActivityTypeCountAggregateOutputType> | number
        }
      }
    }
    Assessment: {
      payload: Prisma.$AssessmentPayload<ExtArgs>
      fields: Prisma.AssessmentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AssessmentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AssessmentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>
        }
        findFirst: {
          args: Prisma.AssessmentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AssessmentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>
        }
        findMany: {
          args: Prisma.AssessmentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>[]
        }
        create: {
          args: Prisma.AssessmentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>
        }
        createMany: {
          args: Prisma.AssessmentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AssessmentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>[]
        }
        delete: {
          args: Prisma.AssessmentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>
        }
        update: {
          args: Prisma.AssessmentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>
        }
        deleteMany: {
          args: Prisma.AssessmentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AssessmentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AssessmentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>[]
        }
        upsert: {
          args: Prisma.AssessmentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentPayload>
        }
        aggregate: {
          args: Prisma.AssessmentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAssessment>
        }
        groupBy: {
          args: Prisma.AssessmentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentGroupByOutputType>[]
        }
        count: {
          args: Prisma.AssessmentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentCountAggregateOutputType> | number
        }
      }
    }
    AssessmentControl: {
      payload: Prisma.$AssessmentControlPayload<ExtArgs>
      fields: Prisma.AssessmentControlFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AssessmentControlFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AssessmentControlFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>
        }
        findFirst: {
          args: Prisma.AssessmentControlFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AssessmentControlFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>
        }
        findMany: {
          args: Prisma.AssessmentControlFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>[]
        }
        create: {
          args: Prisma.AssessmentControlCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>
        }
        createMany: {
          args: Prisma.AssessmentControlCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AssessmentControlCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>[]
        }
        delete: {
          args: Prisma.AssessmentControlDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>
        }
        update: {
          args: Prisma.AssessmentControlUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>
        }
        deleteMany: {
          args: Prisma.AssessmentControlDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AssessmentControlUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AssessmentControlUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>[]
        }
        upsert: {
          args: Prisma.AssessmentControlUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssessmentControlPayload>
        }
        aggregate: {
          args: Prisma.AssessmentControlAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAssessmentControl>
        }
        groupBy: {
          args: Prisma.AssessmentControlGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentControlGroupByOutputType>[]
        }
        count: {
          args: Prisma.AssessmentControlCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssessmentControlCountAggregateOutputType> | number
        }
      }
    }
    SampleType: {
      payload: Prisma.$SampleTypePayload<ExtArgs>
      fields: Prisma.SampleTypeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SampleTypeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SampleTypeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>
        }
        findFirst: {
          args: Prisma.SampleTypeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SampleTypeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>
        }
        findMany: {
          args: Prisma.SampleTypeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>[]
        }
        create: {
          args: Prisma.SampleTypeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>
        }
        createMany: {
          args: Prisma.SampleTypeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SampleTypeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>[]
        }
        delete: {
          args: Prisma.SampleTypeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>
        }
        update: {
          args: Prisma.SampleTypeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>
        }
        deleteMany: {
          args: Prisma.SampleTypeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SampleTypeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SampleTypeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>[]
        }
        upsert: {
          args: Prisma.SampleTypeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SampleTypePayload>
        }
        aggregate: {
          args: Prisma.SampleTypeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSampleType>
        }
        groupBy: {
          args: Prisma.SampleTypeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SampleTypeGroupByOutputType>[]
        }
        count: {
          args: Prisma.SampleTypeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SampleTypeCountAggregateOutputType> | number
        }
      }
    }
    RecordSourceType: {
      payload: Prisma.$RecordSourceTypePayload<ExtArgs>
      fields: Prisma.RecordSourceTypeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecordSourceTypeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecordSourceTypeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>
        }
        findFirst: {
          args: Prisma.RecordSourceTypeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecordSourceTypeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>
        }
        findMany: {
          args: Prisma.RecordSourceTypeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>[]
        }
        create: {
          args: Prisma.RecordSourceTypeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>
        }
        createMany: {
          args: Prisma.RecordSourceTypeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecordSourceTypeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>[]
        }
        delete: {
          args: Prisma.RecordSourceTypeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>
        }
        update: {
          args: Prisma.RecordSourceTypeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>
        }
        deleteMany: {
          args: Prisma.RecordSourceTypeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecordSourceTypeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecordSourceTypeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>[]
        }
        upsert: {
          args: Prisma.RecordSourceTypeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordSourceTypePayload>
        }
        aggregate: {
          args: Prisma.RecordSourceTypeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecordSourceType>
        }
        groupBy: {
          args: Prisma.RecordSourceTypeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecordSourceTypeGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecordSourceTypeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecordSourceTypeCountAggregateOutputType> | number
        }
      }
    }
    Sample: {
      payload: Prisma.$SamplePayload<ExtArgs>
      fields: Prisma.SampleFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SampleFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SampleFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>
        }
        findFirst: {
          args: Prisma.SampleFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SampleFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>
        }
        findMany: {
          args: Prisma.SampleFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>[]
        }
        create: {
          args: Prisma.SampleCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>
        }
        createMany: {
          args: Prisma.SampleCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SampleCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>[]
        }
        delete: {
          args: Prisma.SampleDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>
        }
        update: {
          args: Prisma.SampleUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>
        }
        deleteMany: {
          args: Prisma.SampleDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SampleUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SampleUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>[]
        }
        upsert: {
          args: Prisma.SampleUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SamplePayload>
        }
        aggregate: {
          args: Prisma.SampleAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSample>
        }
        groupBy: {
          args: Prisma.SampleGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SampleGroupByOutputType>[]
        }
        count: {
          args: Prisma.SampleCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SampleCountAggregateOutputType> | number
        }
      }
    }
    AchievementBadge: {
      payload: Prisma.$AchievementBadgePayload<ExtArgs>
      fields: Prisma.AchievementBadgeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AchievementBadgeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AchievementBadgeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>
        }
        findFirst: {
          args: Prisma.AchievementBadgeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AchievementBadgeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>
        }
        findMany: {
          args: Prisma.AchievementBadgeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>[]
        }
        create: {
          args: Prisma.AchievementBadgeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>
        }
        createMany: {
          args: Prisma.AchievementBadgeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AchievementBadgeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>[]
        }
        delete: {
          args: Prisma.AchievementBadgeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>
        }
        update: {
          args: Prisma.AchievementBadgeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>
        }
        deleteMany: {
          args: Prisma.AchievementBadgeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AchievementBadgeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AchievementBadgeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>[]
        }
        upsert: {
          args: Prisma.AchievementBadgeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementBadgePayload>
        }
        aggregate: {
          args: Prisma.AchievementBadgeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAchievementBadge>
        }
        groupBy: {
          args: Prisma.AchievementBadgeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AchievementBadgeGroupByOutputType>[]
        }
        count: {
          args: Prisma.AchievementBadgeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AchievementBadgeCountAggregateOutputType> | number
        }
      }
    }
    UserAchievement: {
      payload: Prisma.$UserAchievementPayload<ExtArgs>
      fields: Prisma.UserAchievementFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserAchievementFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserAchievementFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        findFirst: {
          args: Prisma.UserAchievementFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserAchievementFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        findMany: {
          args: Prisma.UserAchievementFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>[]
        }
        create: {
          args: Prisma.UserAchievementCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        createMany: {
          args: Prisma.UserAchievementCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserAchievementCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>[]
        }
        delete: {
          args: Prisma.UserAchievementDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        update: {
          args: Prisma.UserAchievementUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        deleteMany: {
          args: Prisma.UserAchievementDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserAchievementUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserAchievementUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>[]
        }
        upsert: {
          args: Prisma.UserAchievementUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        aggregate: {
          args: Prisma.UserAchievementAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserAchievement>
        }
        groupBy: {
          args: Prisma.UserAchievementGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserAchievementGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserAchievementCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserAchievementCountAggregateOutputType> | number
        }
      }
    }
    PointTransaction: {
      payload: Prisma.$PointTransactionPayload<ExtArgs>
      fields: Prisma.PointTransactionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PointTransactionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PointTransactionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>
        }
        findFirst: {
          args: Prisma.PointTransactionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PointTransactionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>
        }
        findMany: {
          args: Prisma.PointTransactionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>[]
        }
        create: {
          args: Prisma.PointTransactionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>
        }
        createMany: {
          args: Prisma.PointTransactionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PointTransactionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>[]
        }
        delete: {
          args: Prisma.PointTransactionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>
        }
        update: {
          args: Prisma.PointTransactionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>
        }
        deleteMany: {
          args: Prisma.PointTransactionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PointTransactionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PointTransactionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>[]
        }
        upsert: {
          args: Prisma.PointTransactionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PointTransactionPayload>
        }
        aggregate: {
          args: Prisma.PointTransactionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePointTransaction>
        }
        groupBy: {
          args: Prisma.PointTransactionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PointTransactionGroupByOutputType>[]
        }
        count: {
          args: Prisma.PointTransactionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PointTransactionCountAggregateOutputType> | number
        }
      }
    }
    BehaviorMeasurement: {
      payload: Prisma.$BehaviorMeasurementPayload<ExtArgs>
      fields: Prisma.BehaviorMeasurementFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BehaviorMeasurementFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BehaviorMeasurementFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>
        }
        findFirst: {
          args: Prisma.BehaviorMeasurementFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BehaviorMeasurementFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>
        }
        findMany: {
          args: Prisma.BehaviorMeasurementFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>[]
        }
        create: {
          args: Prisma.BehaviorMeasurementCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>
        }
        createMany: {
          args: Prisma.BehaviorMeasurementCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BehaviorMeasurementCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>[]
        }
        delete: {
          args: Prisma.BehaviorMeasurementDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>
        }
        update: {
          args: Prisma.BehaviorMeasurementUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>
        }
        deleteMany: {
          args: Prisma.BehaviorMeasurementDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BehaviorMeasurementUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BehaviorMeasurementUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>[]
        }
        upsert: {
          args: Prisma.BehaviorMeasurementUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BehaviorMeasurementPayload>
        }
        aggregate: {
          args: Prisma.BehaviorMeasurementAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBehaviorMeasurement>
        }
        groupBy: {
          args: Prisma.BehaviorMeasurementGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BehaviorMeasurementGroupByOutputType>[]
        }
        count: {
          args: Prisma.BehaviorMeasurementCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BehaviorMeasurementCountAggregateOutputType> | number
        }
      }
    }
    EmotionalDriveMetric: {
      payload: Prisma.$EmotionalDriveMetricPayload<ExtArgs>
      fields: Prisma.EmotionalDriveMetricFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EmotionalDriveMetricFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EmotionalDriveMetricFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>
        }
        findFirst: {
          args: Prisma.EmotionalDriveMetricFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EmotionalDriveMetricFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>
        }
        findMany: {
          args: Prisma.EmotionalDriveMetricFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>[]
        }
        create: {
          args: Prisma.EmotionalDriveMetricCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>
        }
        createMany: {
          args: Prisma.EmotionalDriveMetricCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EmotionalDriveMetricCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>[]
        }
        delete: {
          args: Prisma.EmotionalDriveMetricDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>
        }
        update: {
          args: Prisma.EmotionalDriveMetricUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>
        }
        deleteMany: {
          args: Prisma.EmotionalDriveMetricDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EmotionalDriveMetricUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EmotionalDriveMetricUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>[]
        }
        upsert: {
          args: Prisma.EmotionalDriveMetricUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmotionalDriveMetricPayload>
        }
        aggregate: {
          args: Prisma.EmotionalDriveMetricAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEmotionalDriveMetric>
        }
        groupBy: {
          args: Prisma.EmotionalDriveMetricGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EmotionalDriveMetricGroupByOutputType>[]
        }
        count: {
          args: Prisma.EmotionalDriveMetricCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EmotionalDriveMetricCountAggregateOutputType> | number
        }
      }
    }
    Milestone: {
      payload: Prisma.$MilestonePayload<ExtArgs>
      fields: Prisma.MilestoneFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MilestoneFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MilestoneFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>
        }
        findFirst: {
          args: Prisma.MilestoneFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MilestoneFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>
        }
        findMany: {
          args: Prisma.MilestoneFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>[]
        }
        create: {
          args: Prisma.MilestoneCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>
        }
        createMany: {
          args: Prisma.MilestoneCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MilestoneCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>[]
        }
        delete: {
          args: Prisma.MilestoneDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>
        }
        update: {
          args: Prisma.MilestoneUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>
        }
        deleteMany: {
          args: Prisma.MilestoneDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MilestoneUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MilestoneUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>[]
        }
        upsert: {
          args: Prisma.MilestoneUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MilestonePayload>
        }
        aggregate: {
          args: Prisma.MilestoneAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMilestone>
        }
        groupBy: {
          args: Prisma.MilestoneGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MilestoneGroupByOutputType>[]
        }
        count: {
          args: Prisma.MilestoneCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MilestoneCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  username: 'username',
  passwordHash: 'passwordHash',
  role: 'role',
  createdAt: 'createdAt',
  totalPoints: 'totalPoints',
  dailyPointStreak: 'dailyPointStreak',
  lastActivityDate: 'lastActivityDate',
  confidenceInfluencer: 'confidenceInfluencer'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AssuranceActivityTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  defaultLOA: 'defaultLOA',
  createdAt: 'createdAt'
} as const

export type AssuranceActivityTypeScalarFieldEnum = (typeof AssuranceActivityTypeScalarFieldEnum)[keyof typeof AssuranceActivityTypeScalarFieldEnum]


export const ProcessAreaScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  pId: 'pId',
  standard: 'standard'
} as const

export type ProcessAreaScalarFieldEnum = (typeof ProcessAreaScalarFieldEnum)[keyof typeof ProcessAreaScalarFieldEnum]


export const SubProcessScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  processAreaId: 'processAreaId',
  createdAt: 'createdAt'
} as const

export type SubProcessScalarFieldEnum = (typeof SubProcessScalarFieldEnum)[keyof typeof SubProcessScalarFieldEnum]


export const ControlScalarFieldEnum = {
  id: 'id',
  name: 'name',
  statement: 'statement',
  controlType: 'controlType',
  processAreaId: 'processAreaId',
  subProcessId: 'subProcessId',
  isHsseCritical: 'isHsseCritical',
  ramRating: 'ramRating',
  riskWeight: 'riskWeight',
  rawHealthScore: 'rawHealthScore',
  lastTestedDate: 'lastTestedDate',
  lastTestResult: 'lastTestResult',
  createdAt: 'createdAt',
  controlRef: 'controlRef',
  sourceFile: 'sourceFile',
  practiceDocument: 'practiceDocument',
  controlTypeDetail: 'controlTypeDetail',
  csfWho: 'csfWho',
  csfWhat: 'csfWhat',
  csfWhen: 'csfWhen',
  csfWhere: 'csfWhere',
  csfWhy: 'csfWhy',
  csfHow: 'csfHow',
  csfEvidence: 'csfEvidence',
  keyActivities: 'keyActivities',
  riskAddressed: 'riskAddressed',
  testingApproach: 'testingApproach',
  uncertainFlags: 'uncertainFlags',
  standard: 'standard',
  pId: 'pId',
  Requirements: 'Requirements'
} as const

export type ControlScalarFieldEnum = (typeof ControlScalarFieldEnum)[keyof typeof ControlScalarFieldEnum]


export const AssessmentTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AssessmentTemplateScalarFieldEnum = (typeof AssessmentTemplateScalarFieldEnum)[keyof typeof AssessmentTemplateScalarFieldEnum]


export const AssessmentTemplateControlLinkageScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  controlId: 'controlId',
  createdAt: 'createdAt'
} as const

export type AssessmentTemplateControlLinkageScalarFieldEnum = (typeof AssessmentTemplateControlLinkageScalarFieldEnum)[keyof typeof AssessmentTemplateControlLinkageScalarFieldEnum]


export const AssessmentTemplateActivityTypeScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  activityTypeId: 'activityTypeId',
  createdAt: 'createdAt'
} as const

export type AssessmentTemplateActivityTypeScalarFieldEnum = (typeof AssessmentTemplateActivityTypeScalarFieldEnum)[keyof typeof AssessmentTemplateActivityTypeScalarFieldEnum]


export const AssessmentScalarFieldEnum = {
  id: 'id',
  activityTypeId: 'activityTypeId',
  name: 'name',
  assessorId: 'assessorId',
  startDate: 'startDate',
  endDate: 'endDate',
  loa: 'loa',
  status: 'status',
  createdAt: 'createdAt'
} as const

export type AssessmentScalarFieldEnum = (typeof AssessmentScalarFieldEnum)[keyof typeof AssessmentScalarFieldEnum]


export const AssessmentControlScalarFieldEnum = {
  id: 'id',
  assessmentId: 'assessmentId',
  controlId: 'controlId',
  createdAt: 'createdAt'
} as const

export type AssessmentControlScalarFieldEnum = (typeof AssessmentControlScalarFieldEnum)[keyof typeof AssessmentControlScalarFieldEnum]


export const SampleTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
} as const

export type SampleTypeScalarFieldEnum = (typeof SampleTypeScalarFieldEnum)[keyof typeof SampleTypeScalarFieldEnum]


export const RecordSourceTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
} as const

export type RecordSourceTypeScalarFieldEnum = (typeof RecordSourceTypeScalarFieldEnum)[keyof typeof RecordSourceTypeScalarFieldEnum]


export const SampleScalarFieldEnum = {
  id: 'id',
  assessmentId: 'assessmentId',
  sampleTypeId: 'sampleTypeId',
  recordSourceId: 'recordSourceId',
  recordReference: 'recordReference',
  controlEffective: 'controlEffective',
  comment: 'comment',
  status: 'status',
  conclusion: 'conclusion',
  evidenceUrl: 'evidenceUrl',
  createdAt: 'createdAt'
} as const

export type SampleScalarFieldEnum = (typeof SampleScalarFieldEnum)[keyof typeof SampleScalarFieldEnum]


export const AchievementBadgeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  icon: 'icon',
  emotionalDrive: 'emotionalDrive',
  rarity: 'rarity',
  pointsRequired: 'pointsRequired',
  controlsChecked: 'controlsChecked',
  streakDays: 'streakDays',
  achievementType: 'achievementType',
  createdAt: 'createdAt'
} as const

export type AchievementBadgeScalarFieldEnum = (typeof AchievementBadgeScalarFieldEnum)[keyof typeof AchievementBadgeScalarFieldEnum]


export const UserAchievementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  badgeId: 'badgeId',
  earnedAt: 'earnedAt'
} as const

export type UserAchievementScalarFieldEnum = (typeof UserAchievementScalarFieldEnum)[keyof typeof UserAchievementScalarFieldEnum]


export const PointTransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  points: 'points',
  reason: 'reason',
  assessmentId: 'assessmentId',
  sampleId: 'sampleId',
  emotionalDrive: 'emotionalDrive',
  multiplier: 'multiplier',
  createdAt: 'createdAt'
} as const

export type PointTransactionScalarFieldEnum = (typeof PointTransactionScalarFieldEnum)[keyof typeof PointTransactionScalarFieldEnum]


export const BehaviorMeasurementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  date: 'date',
  plansMade: 'plansMade',
  controlsTested: 'controlsTested',
  evidenceDocumented: 'evidenceDocumented',
  teamEngagement: 'teamEngagement',
  qualityScore: 'qualityScore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BehaviorMeasurementScalarFieldEnum = (typeof BehaviorMeasurementScalarFieldEnum)[keyof typeof BehaviorMeasurementScalarFieldEnum]


export const EmotionalDriveMetricScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  period: 'period',
  diversity: 'diversity',
  belonging: 'belonging',
  recognition: 'recognition',
  achievement: 'achievement',
  excellence: 'excellence',
  growth: 'growth',
  contribution: 'contribution',
  security: 'security',
  overallEngagement: 'overallEngagement',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EmotionalDriveMetricScalarFieldEnum = (typeof EmotionalDriveMetricScalarFieldEnum)[keyof typeof EmotionalDriveMetricScalarFieldEnum]


export const MilestoneScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  description: 'description',
  targetValue: 'targetValue',
  currentValue: 'currentValue',
  type: 'type',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
} as const

export type MilestoneScalarFieldEnum = (typeof MilestoneScalarFieldEnum)[keyof typeof MilestoneScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'LOA'
 */
export type EnumLOAFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'LOA'>
    


/**
 * Reference to a field of type 'ControlType'
 */
export type EnumControlTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ControlType'>
    


/**
 * Reference to a field of type 'AssessmentStatus'
 */
export type EnumAssessmentStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AssessmentStatus'>
    


/**
 * Reference to a field of type 'SampleStatus'
 */
export type EnumSampleStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SampleStatus'>
    


/**
 * Reference to a field of type 'SampleConclusion'
 */
export type EnumSampleConclusionFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SampleConclusion'>
    


/**
 * Reference to a field of type 'EmotionalDrive'
 */
export type EnumEmotionalDriveFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'EmotionalDrive'>
    


/**
 * Reference to a field of type 'BadgeRarity'
 */
export type EnumBadgeRarityFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BadgeRarity'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  assuranceActivityType?: Prisma.AssuranceActivityTypeOmit
  processArea?: Prisma.ProcessAreaOmit
  subProcess?: Prisma.SubProcessOmit
  control?: Prisma.ControlOmit
  assessmentTemplate?: Prisma.AssessmentTemplateOmit
  assessmentTemplateControlLinkage?: Prisma.AssessmentTemplateControlLinkageOmit
  assessmentTemplateActivityType?: Prisma.AssessmentTemplateActivityTypeOmit
  assessment?: Prisma.AssessmentOmit
  assessmentControl?: Prisma.AssessmentControlOmit
  sampleType?: Prisma.SampleTypeOmit
  recordSourceType?: Prisma.RecordSourceTypeOmit
  sample?: Prisma.SampleOmit
  achievementBadge?: Prisma.AchievementBadgeOmit
  userAchievement?: Prisma.UserAchievementOmit
  pointTransaction?: Prisma.PointTransactionOmit
  behaviorMeasurement?: Prisma.BehaviorMeasurementOmit
  emotionalDriveMetric?: Prisma.EmotionalDriveMetricOmit
  milestone?: Prisma.MilestoneOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

