
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  AssuranceActivityType: 'AssuranceActivityType',
  ProcessArea: 'ProcessArea',
  SubProcess: 'SubProcess',
  Control: 'Control',
  AssessmentTemplate: 'AssessmentTemplate',
  AssessmentTemplateControlLinkage: 'AssessmentTemplateControlLinkage',
  AssessmentTemplateActivityType: 'AssessmentTemplateActivityType',
  Assessment: 'Assessment',
  AssessmentControl: 'AssessmentControl',
  SampleType: 'SampleType',
  RecordSourceType: 'RecordSourceType',
  Sample: 'Sample',
  AchievementBadge: 'AchievementBadge',
  UserAchievement: 'UserAchievement',
  PointTransaction: 'PointTransaction',
  BehaviorMeasurement: 'BehaviorMeasurement',
  EmotionalDriveMetric: 'EmotionalDriveMetric',
  Milestone: 'Milestone'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  username: 'username',
  passwordHash: 'passwordHash',
  role: 'role',
  createdAt: 'createdAt',
  totalPoints: 'totalPoints',
  dailyPointStreak: 'dailyPointStreak',
  lastActivityDate: 'lastActivityDate',
  confidenceInfluencer: 'confidenceInfluencer'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AssuranceActivityTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  defaultLOA: 'defaultLOA',
  createdAt: 'createdAt'
} as const

export type AssuranceActivityTypeScalarFieldEnum = (typeof AssuranceActivityTypeScalarFieldEnum)[keyof typeof AssuranceActivityTypeScalarFieldEnum]


export const ProcessAreaScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  pId: 'pId',
  standard: 'standard'
} as const

export type ProcessAreaScalarFieldEnum = (typeof ProcessAreaScalarFieldEnum)[keyof typeof ProcessAreaScalarFieldEnum]


export const SubProcessScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  processAreaId: 'processAreaId',
  createdAt: 'createdAt'
} as const

export type SubProcessScalarFieldEnum = (typeof SubProcessScalarFieldEnum)[keyof typeof SubProcessScalarFieldEnum]


export const ControlScalarFieldEnum = {
  id: 'id',
  name: 'name',
  statement: 'statement',
  controlType: 'controlType',
  processAreaId: 'processAreaId',
  subProcessId: 'subProcessId',
  isHsseCritical: 'isHsseCritical',
  ramRating: 'ramRating',
  riskWeight: 'riskWeight',
  rawHealthScore: 'rawHealthScore',
  lastTestedDate: 'lastTestedDate',
  lastTestResult: 'lastTestResult',
  createdAt: 'createdAt',
  controlRef: 'controlRef',
  sourceFile: 'sourceFile',
  practiceDocument: 'practiceDocument',
  controlTypeDetail: 'controlTypeDetail',
  csfWho: 'csfWho',
  csfWhat: 'csfWhat',
  csfWhen: 'csfWhen',
  csfWhere: 'csfWhere',
  csfWhy: 'csfWhy',
  csfHow: 'csfHow',
  csfEvidence: 'csfEvidence',
  keyActivities: 'keyActivities',
  riskAddressed: 'riskAddressed',
  testingApproach: 'testingApproach',
  uncertainFlags: 'uncertainFlags',
  standard: 'standard',
  pId: 'pId',
  Requirements: 'Requirements'
} as const

export type ControlScalarFieldEnum = (typeof ControlScalarFieldEnum)[keyof typeof ControlScalarFieldEnum]


export const AssessmentTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AssessmentTemplateScalarFieldEnum = (typeof AssessmentTemplateScalarFieldEnum)[keyof typeof AssessmentTemplateScalarFieldEnum]


export const AssessmentTemplateControlLinkageScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  controlId: 'controlId',
  createdAt: 'createdAt'
} as const

export type AssessmentTemplateControlLinkageScalarFieldEnum = (typeof AssessmentTemplateControlLinkageScalarFieldEnum)[keyof typeof AssessmentTemplateControlLinkageScalarFieldEnum]


export const AssessmentTemplateActivityTypeScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  activityTypeId: 'activityTypeId',
  createdAt: 'createdAt'
} as const

export type AssessmentTemplateActivityTypeScalarFieldEnum = (typeof AssessmentTemplateActivityTypeScalarFieldEnum)[keyof typeof AssessmentTemplateActivityTypeScalarFieldEnum]


export const AssessmentScalarFieldEnum = {
  id: 'id',
  activityTypeId: 'activityTypeId',
  name: 'name',
  assessorId: 'assessorId',
  startDate: 'startDate',
  endDate: 'endDate',
  loa: 'loa',
  status: 'status',
  createdAt: 'createdAt'
} as const

export type AssessmentScalarFieldEnum = (typeof AssessmentScalarFieldEnum)[keyof typeof AssessmentScalarFieldEnum]


export const AssessmentControlScalarFieldEnum = {
  id: 'id',
  assessmentId: 'assessmentId',
  controlId: 'controlId',
  createdAt: 'createdAt'
} as const

export type AssessmentControlScalarFieldEnum = (typeof AssessmentControlScalarFieldEnum)[keyof typeof AssessmentControlScalarFieldEnum]


export const SampleTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
} as const

export type SampleTypeScalarFieldEnum = (typeof SampleTypeScalarFieldEnum)[keyof typeof SampleTypeScalarFieldEnum]


export const RecordSourceTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
} as const

export type RecordSourceTypeScalarFieldEnum = (typeof RecordSourceTypeScalarFieldEnum)[keyof typeof RecordSourceTypeScalarFieldEnum]


export const SampleScalarFieldEnum = {
  id: 'id',
  assessmentId: 'assessmentId',
  sampleTypeId: 'sampleTypeId',
  recordSourceId: 'recordSourceId',
  recordReference: 'recordReference',
  controlEffective: 'controlEffective',
  comment: 'comment',
  status: 'status',
  conclusion: 'conclusion',
  evidenceUrl: 'evidenceUrl',
  createdAt: 'createdAt'
} as const

export type SampleScalarFieldEnum = (typeof SampleScalarFieldEnum)[keyof typeof SampleScalarFieldEnum]


export const AchievementBadgeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  icon: 'icon',
  emotionalDrive: 'emotionalDrive',
  rarity: 'rarity',
  pointsRequired: 'pointsRequired',
  controlsChecked: 'controlsChecked',
  streakDays: 'streakDays',
  achievementType: 'achievementType',
  createdAt: 'createdAt'
} as const

export type AchievementBadgeScalarFieldEnum = (typeof AchievementBadgeScalarFieldEnum)[keyof typeof AchievementBadgeScalarFieldEnum]


export const UserAchievementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  badgeId: 'badgeId',
  earnedAt: 'earnedAt'
} as const

export type UserAchievementScalarFieldEnum = (typeof UserAchievementScalarFieldEnum)[keyof typeof UserAchievementScalarFieldEnum]


export const PointTransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  points: 'points',
  reason: 'reason',
  assessmentId: 'assessmentId',
  sampleId: 'sampleId',
  emotionalDrive: 'emotionalDrive',
  multiplier: 'multiplier',
  createdAt: 'createdAt'
} as const

export type PointTransactionScalarFieldEnum = (typeof PointTransactionScalarFieldEnum)[keyof typeof PointTransactionScalarFieldEnum]


export const BehaviorMeasurementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  date: 'date',
  plansMade: 'plansMade',
  controlsTested: 'controlsTested',
  evidenceDocumented: 'evidenceDocumented',
  teamEngagement: 'teamEngagement',
  qualityScore: 'qualityScore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BehaviorMeasurementScalarFieldEnum = (typeof BehaviorMeasurementScalarFieldEnum)[keyof typeof BehaviorMeasurementScalarFieldEnum]


export const EmotionalDriveMetricScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  period: 'period',
  diversity: 'diversity',
  belonging: 'belonging',
  recognition: 'recognition',
  achievement: 'achievement',
  excellence: 'excellence',
  growth: 'growth',
  contribution: 'contribution',
  security: 'security',
  overallEngagement: 'overallEngagement',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EmotionalDriveMetricScalarFieldEnum = (typeof EmotionalDriveMetricScalarFieldEnum)[keyof typeof EmotionalDriveMetricScalarFieldEnum]


export const MilestoneScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  description: 'description',
  targetValue: 'targetValue',
  currentValue: 'currentValue',
  type: 'type',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
} as const

export type MilestoneScalarFieldEnum = (typeof MilestoneScalarFieldEnum)[keyof typeof MilestoneScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

